package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:19:07 by Hibernate Tools 3.2.1.GA



/**
 * AliquotasImpressora generated by hbm2java
 */
public class AliquotasImpressora  implements java.io.Serializable {


     private int id;
     private Double aliquota;
     private boolean iss;
     private boolean icms;

    public AliquotasImpressora() {
    }

	
    public AliquotasImpressora(int id) {
        this.id = id;
    }
    public AliquotasImpressora(int id, Double aliquota, boolean ISS, boolean ICMS) {
       this.id = id;
       this.aliquota = aliquota;
       this.iss = ISS;
       this.icms = ICMS;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Double getAliquota() {
        return this.aliquota;
    }
    
    public void setAliquota(Double aliquota) {
        this.aliquota = aliquota;
    }

    public boolean getIss() {
        return this.iss;
    }
    
    public void setIss(boolean iss) {
        this.iss = iss;
    }
    public boolean getIcms() {
        return this.icms;
    }
    
    public void setIcms(boolean icms) {
        this.icms = icms;
    }



}


