package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:19:07 by Hibernate Tools 3.2.1.GA



/**
 * ConfiguracoesSistema generated by hbm2java
 */
public class ConfiguracoesSistema  implements java.io.Serializable {

     private int id;
     private int corPadrao;
     private String mensagemPromocional;
     private String portaSerial;
     private String md5;
     private String grandeTotal;
     private String numeroSerie;
     private Integer fkBrLojaId;

    public ConfiguracoesSistema() {
    }

	
    public ConfiguracoesSistema(int id, int corPadrao, String portaSerial) {
        this.id = id;
        this.corPadrao = corPadrao;
        this.portaSerial = portaSerial;
    }
    public ConfiguracoesSistema(int id, int corPadrao, String mensagemPromocional, String portaSerial, String md5, String grandeTotal, String numeroSerie, Integer fkBrLojaId) {
       this.id = id;
       this.corPadrao = corPadrao;
       this.mensagemPromocional = mensagemPromocional;
       this.portaSerial = portaSerial;
       this.md5 = md5;
       this.grandeTotal = grandeTotal;
       this.numeroSerie = numeroSerie;
       this.fkBrLojaId = fkBrLojaId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getCorPadrao() {
        return this.corPadrao;
    }
    
    public void setCorPadrao(int corPadrao) {
        this.corPadrao = corPadrao;
    }
    public String getMensagemPromocional() {
        return this.mensagemPromocional;
    }
    
    public void setMensagemPromocional(String mensagemPromocional) {
        this.mensagemPromocional = mensagemPromocional;
    }
    public String getPortaSerial() {
        return this.portaSerial;
    }
    
    public void setPortaSerial(String portaSerial) {
        this.portaSerial = portaSerial;
    }
    public String getMd5() {
        return this.md5;
    }
    
    public void setMd5(String md5) {
        this.md5 = md5;
    }
    public String getGrandeTotal() {
        return this.grandeTotal;
    }
    
    public void setGrandeTotal(String grandeTotal) {
        this.grandeTotal = grandeTotal;
    }
    public String getNumeroSerie() {
        return this.numeroSerie;
    }
    
    public void setNumeroSerie(String numeroSerie) {
        this.numeroSerie = numeroSerie;
    }
    public Integer getFkBrLojaId() {
        return this.fkBrLojaId;
    }
    
    public void setFkBrLojaId(Integer fkBrLojaId) {
        this.fkBrLojaId = fkBrLojaId;
    }




}


