package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:19:07 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DiaFiscal generated by hbm2java
 */
public class DiaFiscal extends Entity implements java.io.Serializable {

     private int id;
     private FechaCaixa fechaCaixa;
     private AbreCaixa abreCaixa;
     private Set ecfReducoeszs = new HashSet(0);
     private Set ecfSuprimentoses = new HashSet(0);
     private Set ecfSangriases = new HashSet(0);

    public DiaFiscal() {
    }

	
    public DiaFiscal(int id, Date dataHora) {
        this.id = id;
        this.dataHora = dataHora;
    }
    public DiaFiscal(int id, FechaCaixa fechaCaixa, AbreCaixa abreCaixa, Date dataHora, Set ecfReducoeszs, Set ecfSuprimentoses, Set ecfSangriases) {
       this.id = id;
       this.fechaCaixa = fechaCaixa;
       this.abreCaixa = abreCaixa;
       this.dataHora = dataHora;
       this.ecfReducoeszs = ecfReducoeszs;
       this.ecfSuprimentoses = ecfSuprimentoses;
       this.ecfSangriases = ecfSangriases;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public FechaCaixa getFechaCaixa() {
        return this.fechaCaixa;
    }
    
    public void setFechaCaixa(FechaCaixa fechaCaixa) {
        this.fechaCaixa = fechaCaixa;
    }
    public AbreCaixa getAbreCaixa() {
        return this.abreCaixa;
    }
    
    public void setAbreCaixa(AbreCaixa abreCaixa) {
        this.abreCaixa = abreCaixa;
    }
    
    public Set getEcfReducoeszs() {
        return this.ecfReducoeszs;
    }
    
    public void setEcfReducoeszs(Set ecfReducoeszs) {
        this.ecfReducoeszs = ecfReducoeszs;
    }
    public Set getEcfSuprimentoses() {
        return this.ecfSuprimentoses;
    }
    
    public void setEcfSuprimentoses(Set ecfSuprimentoses) {
        this.ecfSuprimentoses = ecfSuprimentoses;
    }
    public Set getEcfSangriases() {
        return this.ecfSangriases;
    }
    
    public void setEcfSangriases(Set ecfSangriases) {
        this.ecfSangriases = ecfSangriases;
    }

}


