package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:19:07 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * EcfComprador generated by hbm2java
 */
public class EcfComprador  implements java.io.Serializable {


     private int id;
     private String cpfCnpj;
     private String nome;
     private String endereco;
     private Set vendases = new HashSet(0);

    public EcfComprador() {
    }

	
    public EcfComprador(int id, String cpfCnpj) {
        this.id = id;
        this.cpfCnpj = cpfCnpj;
    }
    public EcfComprador(int id, String cpfCnpj, String nome, String endereco, Set vendases) {
       this.id = id;
       this.cpfCnpj = cpfCnpj;
       this.nome = nome;
       this.endereco = endereco;
       this.vendases = vendases;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCpfCnpj() {
        return this.cpfCnpj;
    }
    
    public void setCpfCnpj(String cpfCnpj) {
        this.cpfCnpj = cpfCnpj;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public Set getVendases() {
        return this.vendases;
    }
    
    public void setVendases(Set vendases) {
        this.vendases = vendases;
    }




}


