package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:19:07 by Hibernate Tools 3.2.1.GA



/**
 * EcfEcfsAutorizados generated by hbm2java
 */
public class EcfEcfsAutorizados  implements java.io.Serializable {


     private int id;
     private String numeroFab;

    public EcfEcfsAutorizados() {
    }

    public EcfEcfsAutorizados(int id, String numeroFab) {
       this.id = id;
       this.numeroFab = numeroFab;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNumeroFab() {
        return this.numeroFab;
    }
    
    public void setNumeroFab(String numeroFab) {
        this.numeroFab = numeroFab;
    }




}


