package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:19:07 by Hibernate Tools 3.2.1.GA



/**
 * EcfExecutaveis generated by hbm2java
 */
public class EcfExecutaveis  implements java.io.Serializable {


     private int id;
     private String nome;
     private String path;
     private String md5;

    public EcfExecutaveis() {
    }

    public EcfExecutaveis(int id, String nome, String path, String md5) {
       this.id = id;
       this.nome = nome;
       this.path = path;
       this.md5 = md5;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public String getMd5() {
        return this.md5;
    }
    
    public void setMd5(String md5) {
        this.md5 = md5;
    }




}


