package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:19:07 by Hibernate Tools 3.2.1.GA



/**
 * EcfIdentificacao generated by hbm2java
 */
public class EcfIdentificacao  implements java.io.Serializable {


     private int id;
     private String laudo;
     private String shCnpj;
     private String shRazaoSocial;
     private String shEndereco;
     private String shTelefone;
     private String shContato;
     private String pafNomeComercial;
     private String pafVersao;
     private String pafPrincipalExecutavel;
     private String pafArqTxtExe;
     private String pafVersaoEr;
     private String shInscricaoEstadual;
     private String shInscricaoMunicipal;
     private String bancoDeDados;
     private String linguagemProgramacao;

    public EcfIdentificacao() {
    }

	
    public EcfIdentificacao(int id) {
        this.id = id;
    }
    public EcfIdentificacao(int id, String laudo, String shCnpj, String shRazaoSocial, String shEndereco, String shTelefone, String shContato, String pafNomeComercial, String pafVersao, String pafPrincipalExecutavel, String pafArqTxtExe, String pafVersaoEr, String shInscricaoEstadual, String shInscricaoMunicipal, String bancoDeDados, String linguagemProgramacao) {
       this.id = id;
       this.laudo = laudo;
       this.shCnpj = shCnpj;
       this.shRazaoSocial = shRazaoSocial;
       this.shEndereco = shEndereco;
       this.shTelefone = shTelefone;
       this.shContato = shContato;
       this.pafNomeComercial = pafNomeComercial;
       this.pafVersao = pafVersao;
       this.pafPrincipalExecutavel = pafPrincipalExecutavel;
       this.pafArqTxtExe = pafArqTxtExe;
       this.pafVersaoEr = pafVersaoEr;
       this.shInscricaoEstadual = shInscricaoEstadual;
       this.shInscricaoMunicipal = shInscricaoMunicipal;
       this.bancoDeDados = bancoDeDados;
       this.linguagemProgramacao = linguagemProgramacao;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLaudo() {
        return this.laudo;
    }
    
    public void setLaudo(String laudo) {
        this.laudo = laudo;
    }
    public String getShCnpj() {
        return this.shCnpj;
    }
    
    public void setShCnpj(String shCnpj) {
        this.shCnpj = shCnpj;
    }
    public String getShRazaoSocial() {
        return this.shRazaoSocial;
    }
    
    public void setShRazaoSocial(String shRazaoSocial) {
        this.shRazaoSocial = shRazaoSocial;
    }
    public String getShEndereco() {
        return this.shEndereco;
    }
    
    public void setShEndereco(String shEndereco) {
        this.shEndereco = shEndereco;
    }
    public String getShTelefone() {
        return this.shTelefone;
    }
    
    public void setShTelefone(String shTelefone) {
        this.shTelefone = shTelefone;
    }
    public String getShContato() {
        return this.shContato;
    }
    
    public void setShContato(String shContato) {
        this.shContato = shContato;
    }
    public String getPafNomeComercial() {
        return this.pafNomeComercial;
    }
    
    public void setPafNomeComercial(String pafNomeComercial) {
        this.pafNomeComercial = pafNomeComercial;
    }
    public String getPafVersao() {
        return this.pafVersao;
    }
    
    public void setPafVersao(String pafVersao) {
        this.pafVersao = pafVersao;
    }
    public String getPafPrincipalExecutavel() {
        return this.pafPrincipalExecutavel;
    }
    
    public void setPafPrincipalExecutavel(String pafPrincipalExecutavel) {
        this.pafPrincipalExecutavel = pafPrincipalExecutavel;
    }
    public String getPafArqTxtExe() {
        return this.pafArqTxtExe;
    }
    
    public void setPafArqTxtExe(String pafArqTxtExe) {
        this.pafArqTxtExe = pafArqTxtExe;
    }
    public String getPafVersaoEr() {
        return this.pafVersaoEr;
    }
    
    public void setPafVersaoEr(String pafVersaoEr) {
        this.pafVersaoEr = pafVersaoEr;
    }
    public String getShInscricaoEstadual() {
        return this.shInscricaoEstadual;
    }
    
    public void setShInscricaoEstadual(String shInscricaoEstadual) {
        this.shInscricaoEstadual = shInscricaoEstadual;
    }
    public String getShInscricaoMunicipal() {
        return this.shInscricaoMunicipal;
    }
    
    public void setShInscricaoMunicipal(String shInscricaoMunicipal) {
        this.shInscricaoMunicipal = shInscricaoMunicipal;
    }

    public String getBancoDeDados() {
        return this.bancoDeDados;
    }
    
    public void setBancoDeDados(String bancoDeDados) {
        this.bancoDeDados = bancoDeDados;
    }
    
    public String getLinguagemProgramacao() {
        return this.linguagemProgramacao;
    }
    
    public void setLinguagemProgramacao(String linguagemProgramacao) {
        this.linguagemProgramacao = linguagemProgramacao;
    }



}


