package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:19:07 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EcfLeiturasx generated by hbm2java
 */
public class EcfLeiturasx  implements java.io.Serializable {


     private Integer id;
     private Date dataHora;

    public EcfLeiturasx() {
    }

    public EcfLeiturasx(Integer id, Date dataHora) {
       this.id = id;
       this.dataHora = dataHora;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getDataHora() {
        return this.dataHora;
    }
    
    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }




}


