package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:19:07 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EcfReducoesz generated by hbm2java
 */
public class EcfReducoesz extends Entity implements java.io.Serializable {


     private int id;
     private DiaFiscal diaFiscal;
     private Date dataHora;

    public EcfReducoesz() {
    }

    public EcfReducoesz(int id, DiaFiscal diaFiscal, Date dataHora) {
       this.id = id;
       this.diaFiscal = diaFiscal;
       this.dataHora = dataHora;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public DiaFiscal getDiaFiscal() {
        return this.diaFiscal;
    }
    
    public void setDiaFiscal(DiaFiscal diaFiscal) {
        this.diaFiscal = diaFiscal;
    }
    public Date getDataHora() {
        return this.dataHora;
    }

    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }




}


