package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:19:07 by Hibernate Tools 3.2.1.GA



/**
 * EcfRelatoriosGerenciais generated by hbm2java
 */
public class EcfRelatoriosGerenciais  implements java.io.Serializable {


     private int id;
     private int tipo;
     private String indiceGerencial;

    public EcfRelatoriosGerenciais() {
    }

    public EcfRelatoriosGerenciais(int id, int tipo, String indiceGerencial) {
       this.id = id;
       this.tipo = tipo;
       this.indiceGerencial = indiceGerencial;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }
    public String getIndiceGerencial() {
        return this.indiceGerencial;
    }
    
    public void setIndiceGerencial(String indiceGerencial) {
        this.indiceGerencial = indiceGerencial;
    }




}


