package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:19:07 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EcfSuprimentos generated by hbm2java
 */
public class EcfSuprimentos extends Entity implements java.io.Serializable {

     private int id;
     private DiaFiscal diaFiscal;
     private double valor;

    public EcfSuprimentos() {
    }

    public EcfSuprimentos(int id, DiaFiscal diaFiscal, double valor, Date dataHora) {
       this.id = id;
       this.diaFiscal = diaFiscal;
       this.valor = valor;
       this.dataHora = dataHora;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public DiaFiscal getDiaFiscal() {
        return this.diaFiscal;
    }
    
    public void setDiaFiscal(DiaFiscal diaFiscal) {
        this.diaFiscal = diaFiscal;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public Date getDataHora() {
        return this.dataHora;
    }
    
    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }




}


