package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:19:07 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FechaCaixa generated by hbm2java
 */
public class FechaCaixa extends Entity implements java.io.Serializable {

     private int id;
     private Set diaFiscals = new HashSet(0);

    public FechaCaixa() {
    }

	
    public FechaCaixa(int id, Date dataHora) {
        this.id = id;
        this.dataHora = dataHora;
    }
    public FechaCaixa(int id, Date dataHora, Set diaFiscals) {
       this.id = id;
       this.dataHora = dataHora;
       this.diaFiscals = diaFiscals;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Set getDiaFiscals() {
        return this.diaFiscals;
    }
    
    public void setDiaFiscals(Set diaFiscals) {
        this.diaFiscals = diaFiscals;
    }

}


