package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:19:07 by Hibernate Tools 3.2.1.GA



/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private int id;
     private Vendas vendas;
     private Long codigo;
     private String descricao;
     private Double aliquota;
     private Integer tipoQuantidade;
     private Double quantidade;
     private Integer casasDecimais;
     private Double preco;
     private Integer tipoDesconto;
     private Double valorDesconto;
     private Integer status;

    public Item() {
    }

	
    public Item(int id) {
        this.id = id;
    }
    public Item(int id, Vendas vendas, Long codigo, String descricao, Double aliquota, Integer tipoQuantidade, Double quantidade, Integer casasDecimais, Double preco, Integer tipoDesconto, Double valorDesconto, Integer status) {
       this.id = id;
       this.vendas = vendas;
       this.codigo = codigo;
       this.descricao = descricao;
       this.aliquota = aliquota;
       this.tipoQuantidade = tipoQuantidade;
       this.quantidade = quantidade;
       this.casasDecimais = casasDecimais;
       this.preco = preco;
       this.tipoDesconto = tipoDesconto;
       this.valorDesconto = valorDesconto;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Vendas getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Vendas vendas) {
        this.vendas = vendas;
    }
    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Double getAliquota() {
        return this.aliquota;
    }
    
    public void setAliquota(Double aliquota) {
        this.aliquota = aliquota;
    }
    public Integer getTipoQuantidade() {
        return this.tipoQuantidade;
    }
    
    public void setTipoQuantidade(Integer tipoQuantidade) {
        this.tipoQuantidade = tipoQuantidade;
    }
    public Double getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Double quantidade) {
        this.quantidade = quantidade;
    }
    public Integer getCasasDecimais() {
        return this.casasDecimais;
    }
    
    public void setCasasDecimais(Integer casasDecimais) {
        this.casasDecimais = casasDecimais;
    }
    public Double getPreco() {
        return this.preco;
    }
    
    public void setPreco(Double preco) {
        this.preco = preco;
    }
    public Integer getTipoDesconto() {
        return this.tipoDesconto;
    }
    
    public void setTipoDesconto(Integer tipoDesconto) {
        this.tipoDesconto = tipoDesconto;
    }
    public Double getValorDesconto() {
        return this.valorDesconto;
    }
    
    public void setValorDesconto(Double valorDesconto) {
        this.valorDesconto = valorDesconto;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


