package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:50:02 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * PafMeiosPagamentoDia generated by hbm2java
 */
public class PafMeiosPagamentoDia  implements java.io.Serializable {


     private int id;
     private TipoDocumento tipoDocumento;
     private BigDecimal valor;
     private Date datahora;
     private int fkBrCodigoPagDetalhado;

    public PafMeiosPagamentoDia() {
    }

    public PafMeiosPagamentoDia(int id, TipoDocumento tipoDocumento, BigDecimal valor, Date datahora, int fkBrCodigoPagDetalhado) {
       this.id = id;
       this.tipoDocumento = tipoDocumento;
       this.valor = valor;
       this.datahora = datahora;
       this.fkBrCodigoPagDetalhado = fkBrCodigoPagDetalhado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TipoDocumento getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(TipoDocumento tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public Date getDatahora() {
        return this.datahora;
    }
    
    public void setDatahora(Date datahora) {
        this.datahora = datahora;
    }
    public int getFkBrCodigoPagDetalhado() {
        return this.fkBrCodigoPagDetalhado;
    }
    
    public void setFkBrCodigoPagDetalhado(int fkBrCodigoPagDetalhado) {
        this.fkBrCodigoPagDetalhado = fkBrCodigoPagDetalhado;
    }




}


