package br.com.sinetic.pafecftef.entities;
// Generated 11-Mar-2013 10:11:53 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * PafRegR07 generated by hbm2java
 */
public class PafRegR07  implements java.io.Serializable {


     private int id;
     private String numeroFabricacao;
     private char mfAdicional;
     private String modeloEcf;
     private int numeroUsuario;
     private int coo;
     private int ccf;
     private int gnf;
     private int fkCfpdBrMeioPagamento;
     private BigDecimal valorPago;
     private char indicadorEstorno;
     private BigDecimal valorEstornado;

    public PafRegR07() {
    }

    public PafRegR07(int id, String numeroFabricacao, char mfAdicional, String modeloEcf, int numeroUsuario, int coo, int ccf, int gnf, int fkCfpdBrMeioPagamento, BigDecimal valorPago, char indicadorEstorno, BigDecimal valorEstornado) {
       this.id = id;
       this.numeroFabricacao = numeroFabricacao;
       this.mfAdicional = mfAdicional;
       this.modeloEcf = modeloEcf;
       this.numeroUsuario = numeroUsuario;
       this.coo = coo;
       this.ccf = ccf;
       this.gnf = gnf;
       this.fkCfpdBrMeioPagamento = fkCfpdBrMeioPagamento;
       this.valorPago = valorPago;
       this.indicadorEstorno = indicadorEstorno;
       this.valorEstornado = valorEstornado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNumeroFabricacao() {
        return this.numeroFabricacao;
    }
    
    public void setNumeroFabricacao(String numeroFabricacao) {
        this.numeroFabricacao = numeroFabricacao;
    }
    public char getMfAdicional() {
        return this.mfAdicional;
    }
    
    public void setMfAdicional(char mfAdicional) {
        this.mfAdicional = mfAdicional;
    }
    public String getModeloEcf() {
        return this.modeloEcf;
    }
    
    public void setModeloEcf(String modeloEcf) {
        this.modeloEcf = modeloEcf;
    }
    public int getNumeroUsuario() {
        return this.numeroUsuario;
    }
    
    public void setNumeroUsuario(int numeroUsuario) {
        this.numeroUsuario = numeroUsuario;
    }
    public int getCoo() {
        return this.coo;
    }
    
    public void setCoo(int coo) {
        this.coo = coo;
    }
    public int getCcf() {
        return this.ccf;
    }
    
    public void setCcf(int ccf) {
        this.ccf = ccf;
    }
    public int getGnf() {
        return this.gnf;
    }
    
    public void setGnf(int gnf) {
        this.gnf = gnf;
    }
    public int getFkCfpdBrMeioPagamento() {
        return this.fkCfpdBrMeioPagamento;
    }
    
    public void setFkCfpdBrMeioPagamento(int fkCfpdBrMeioPagamento) {
        this.fkCfpdBrMeioPagamento = fkCfpdBrMeioPagamento;
    }
    public BigDecimal getValorPago() {
        return this.valorPago;
    }
    
    public void setValorPago(BigDecimal valorPago) {
        this.valorPago = valorPago;
    }
    public char getIndicadorEstorno() {
        return this.indicadorEstorno;
    }
    
    public void setIndicadorEstorno(char indicadorEstorno) {
        this.indicadorEstorno = indicadorEstorno;
    }
    public BigDecimal getValorEstornado() {
        return this.valorEstornado;
    }
    
    public void setValorEstornado(BigDecimal valorEstornado) {
        this.valorEstornado = valorEstornado;
    }




}


