package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:53:03 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PafRegR04 generated by hbm2java
 */
public class PafRegR04  implements java.io.Serializable {


     private int id;
     private String numeroFabEcf;
     private char mfAdicional;
     private String modeloEcf;
     private String numeroUsuario;
     private int ccfCvcCbp;
     private int coo;
     private Date dataInicio;
     private double subtotal;
     private double descontoSubtotal;
     private char tipoDescontoSubtotal;
     private double acrescimoSubtotal;
     private char tipoAcrescimoSubtotal;
     private double totalLiquido;
     private boolean indicadorCancelamento;
     private double cancelamentoAcrescimoSubtotal;
     private char ordemAplicacaoDescAcresc;
     private String nomeCliente;
     private String cpfCnpj;

    public PafRegR04() {
    }

    public PafRegR04(int id, String numeroFabEcf, char mfAdicional, String modeloEcf, String numeroUsuario, int ccfCvcCbp, int coo, Date dataInicio, double subtotal, double descontoSubtotal, char tipoDescontoSubtotal, double acrescimoSubtotal, char tipoAcrescimoSubtotal, double totalLiquido, boolean indicadorCancelamento, double cancelamentoAcrescimoSubtotal, char ordemAplicacaoDescAcresc, String nomeCliente, String cpfCnpj) {
       this.id = id;
       this.numeroFabEcf = numeroFabEcf;
       this.mfAdicional = mfAdicional;
       this.modeloEcf = modeloEcf;
       this.numeroUsuario = numeroUsuario;
       this.ccfCvcCbp = ccfCvcCbp;
       this.coo = coo;
       this.dataInicio = dataInicio;
       this.subtotal = subtotal;
       this.descontoSubtotal = descontoSubtotal;
       this.tipoDescontoSubtotal = tipoDescontoSubtotal;
       this.acrescimoSubtotal = acrescimoSubtotal;
       this.tipoAcrescimoSubtotal = tipoAcrescimoSubtotal;
       this.totalLiquido = totalLiquido;
       this.indicadorCancelamento = indicadorCancelamento;
       this.cancelamentoAcrescimoSubtotal = cancelamentoAcrescimoSubtotal;
       this.ordemAplicacaoDescAcresc = ordemAplicacaoDescAcresc;
       this.nomeCliente = nomeCliente;
       this.cpfCnpj = cpfCnpj;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNumeroFabEcf() {
        return this.numeroFabEcf;
    }
    
    public void setNumeroFabEcf(String numeroFabEcf) {
        this.numeroFabEcf = numeroFabEcf;
    }
    public char getMfAdicional() {
        return this.mfAdicional;
    }
    
    public void setMfAdicional(char mfAdicional) {
        this.mfAdicional = mfAdicional;
    }
    public String getModeloEcf() {
        return this.modeloEcf;
    }
    
    public void setModeloEcf(String modeloEcf) {
        this.modeloEcf = modeloEcf;
    }
    public String getNumeroUsuario() {
        return this.numeroUsuario;
    }
    
    public void setNumeroUsuario(String numeroUsuario) {
        this.numeroUsuario = numeroUsuario;
    }
    public int getCcfCvcCbp() {
        return this.ccfCvcCbp;
    }
    
    public void setCcfCvcCbp(int ccfCvcCbp) {
        this.ccfCvcCbp = ccfCvcCbp;
    }
    public int getCoo() {
        return this.coo;
    }
    
    public void setCoo(int coo) {
        this.coo = coo;
    }
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }
    public double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }
    public double getDescontoSubtotal() {
        return this.descontoSubtotal;
    }
    
    public void setDescontoSubtotal(double descontoSubtotal) {
        this.descontoSubtotal = descontoSubtotal;
    }
    public char getTipoDescontoSubtotal() {
        return this.tipoDescontoSubtotal;
    }
    
    public void setTipoDescontoSubtotal(char tipoDescontoSubtotal) {
        this.tipoDescontoSubtotal = tipoDescontoSubtotal;
    }
    public double getAcrescimoSubtotal() {
        return this.acrescimoSubtotal;
    }
    
    public void setAcrescimoSubtotal(double acrescimoSubtotal) {
        this.acrescimoSubtotal = acrescimoSubtotal;
    }
    public char getTipoAcrescimoSubtotal() {
        return this.tipoAcrescimoSubtotal;
    }
    
    public void setTipoAcrescimoSubtotal(char tipoAcrescimoSubtotal) {
        this.tipoAcrescimoSubtotal = tipoAcrescimoSubtotal;
    }
    public double getTotalLiquido() {
        return this.totalLiquido;
    }
    
    public void setTotalLiquido(double totalLiquido) {
        this.totalLiquido = totalLiquido;
    }
    public boolean isIndicadorCancelamento() {
        return this.indicadorCancelamento;
    }
    
    public void setIndicadorCancelamento(boolean indicadorCancelamento) {
        this.indicadorCancelamento = indicadorCancelamento;
    }
    public double getCancelamentoAcrescimoSubtotal() {
        return this.cancelamentoAcrescimoSubtotal;
    }
    
    public void setCancelamentoAcrescimoSubtotal(double cancelamentoAcrescimoSubtotal) {
        this.cancelamentoAcrescimoSubtotal = cancelamentoAcrescimoSubtotal;
    }
    public char getOrdemAplicacaoDescAcresc() {
        return this.ordemAplicacaoDescAcresc;
    }
    
    public void setOrdemAplicacaoDescAcresc(char ordemAplicacaoDescAcresc) {
        this.ordemAplicacaoDescAcresc = ordemAplicacaoDescAcresc;
    }
    public String getNomeCliente() {
        return this.nomeCliente;
    }
    
    public void setNomeCliente(String nomeCliente) {
        this.nomeCliente = nomeCliente;
    }
    public String getCpfCnpj() {
        return this.cpfCnpj;
    }
    
    public void setCpfCnpj(String cpfCnpj) {
        this.cpfCnpj = cpfCnpj;
    }




}


