package br.com.sinetic.pafecftef.entities;
// Generated 12-Mar-2013 14:47:07 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * PafRegR05 generated by hbm2java
 */
public class PafRegR05  implements java.io.Serializable {


     private int id;
     private String numeroFabricacao;
     private char mfAdicional;
     private String modeloEcf;
     private String numeroUsuario;
     private int coo;
     private int ccfCvcCbp;
     private int numeroItem;
     private int codProduto;
     private String descricao;
     private int quantidade;
     private String unidade;
     private BigDecimal valorUnitario;
     private BigDecimal descontoItem;
     private BigDecimal acrescimoItem;
     private BigDecimal valorTotalLiq;
     private String totalizadorParcial;
     private char indicadorCancelamento;
     private int quantidadeCancelada;
     private BigDecimal valorCancelado;
     private BigDecimal cancelamentoAcrescimo;
     private char iat;
     private char ippt;
     private int casasQnt;
     private int casasValor;

    public PafRegR05() {
    }

    public PafRegR05(int id, String numeroFabricacao, char mfAdicional, String modeloEcf, String numeroUsuario, int coo, int ccfCvcCbp, int numeroItem, int codProduto, String descricao, int quantidade, String unidade, BigDecimal valorUnitario, BigDecimal descontoItem, BigDecimal acrescimoItem, BigDecimal valorTotalLiq, String totalizadorParcial, char indicadorCancelamento, int quantidadeCancelada, BigDecimal valorCancelado, BigDecimal cancelamentoAcrescimo, char iat, char ippt, int casasQnt, int casasValor) {
       this.id = id;
       this.numeroFabricacao = numeroFabricacao;
       this.mfAdicional = mfAdicional;
       this.modeloEcf = modeloEcf;
       this.numeroUsuario = numeroUsuario;
       this.coo = coo;
       this.ccfCvcCbp = ccfCvcCbp;
       this.numeroItem = numeroItem;
       this.codProduto = codProduto;
       this.descricao = descricao;
       this.quantidade = quantidade;
       this.unidade = unidade;
       this.valorUnitario = valorUnitario;
       this.descontoItem = descontoItem;
       this.acrescimoItem = acrescimoItem;
       this.valorTotalLiq = valorTotalLiq;
       this.totalizadorParcial = totalizadorParcial;
       this.indicadorCancelamento = indicadorCancelamento;
       this.quantidadeCancelada = quantidadeCancelada;
       this.valorCancelado = valorCancelado;
       this.cancelamentoAcrescimo = cancelamentoAcrescimo;
       this.iat = iat;
       this.ippt = ippt;
       this.casasQnt = casasQnt;
       this.casasValor = casasValor;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNumeroFabricacao() {
        return this.numeroFabricacao;
    }
    
    public void setNumeroFabricacao(String numeroFabricacao) {
        this.numeroFabricacao = numeroFabricacao;
    }
    public char getMfAdicional() {
        return this.mfAdicional;
    }
    
    public void setMfAdicional(char mfAdicional) {
        this.mfAdicional = mfAdicional;
    }
    public String getModeloEcf() {
        return this.modeloEcf;
    }
    
    public void setModeloEcf(String modeloEcf) {
        this.modeloEcf = modeloEcf;
    }
    public String getNumeroUsuario() {
        return this.numeroUsuario;
    }
    
    public void setNumeroUsuario(String numeroUsuario) {
        this.numeroUsuario = numeroUsuario;
    }
    public int getCoo() {
        return this.coo;
    }
    
    public void setCoo(int coo) {
        this.coo = coo;
    }
    public int getCcfCvcCbp() {
        return this.ccfCvcCbp;
    }
    
    public void setCcfCvcCbp(int ccfCvcCbp) {
        this.ccfCvcCbp = ccfCvcCbp;
    }
    public int getNumeroItem() {
        return this.numeroItem;
    }
    
    public void setNumeroItem(int numeroItem) {
        this.numeroItem = numeroItem;
    }
    public int getCodProduto() {
        return this.codProduto;
    }
    
    public void setCodProduto(int codProduto) {
        this.codProduto = codProduto;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public String getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(String unidade) {
        this.unidade = unidade;
    }
    public BigDecimal getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(BigDecimal valorUnitario) {
        this.valorUnitario = valorUnitario;
    }
    public BigDecimal getDescontoItem() {
        return this.descontoItem;
    }
    
    public void setDescontoItem(BigDecimal descontoItem) {
        this.descontoItem = descontoItem;
    }
    public BigDecimal getAcrescimoItem() {
        return this.acrescimoItem;
    }
    
    public void setAcrescimoItem(BigDecimal acrescimoItem) {
        this.acrescimoItem = acrescimoItem;
    }
    public BigDecimal getValorTotalLiq() {
        return this.valorTotalLiq;
    }
    
    public void setValorTotalLiq(BigDecimal valorTotalLiq) {
        this.valorTotalLiq = valorTotalLiq;
    }
    public String getTotalizadorParcial() {
        return this.totalizadorParcial;
    }
    
    public void setTotalizadorParcial(String totalizadorParcial) {
        this.totalizadorParcial = totalizadorParcial;
    }
    public char getIndicadorCancelamento() {
        return this.indicadorCancelamento;
    }
    
    public void setIndicadorCancelamento(char indicadorCancelamento) {
        this.indicadorCancelamento = indicadorCancelamento;
    }
    public int getQuantidadeCancelada() {
        return this.quantidadeCancelada;
    }
    
    public void setQuantidadeCancelada(int quantidadeCancelada) {
        this.quantidadeCancelada = quantidadeCancelada;
    }
    public BigDecimal getValorCancelado() {
        return this.valorCancelado;
    }
    
    public void setValorCancelado(BigDecimal valorCancelado) {
        this.valorCancelado = valorCancelado;
    }
    public BigDecimal getCancelamentoAcrescimo() {
        return this.cancelamentoAcrescimo;
    }
    
    public void setCancelamentoAcrescimo(BigDecimal cancelamentoAcrescimo) {
        this.cancelamentoAcrescimo = cancelamentoAcrescimo;
    }
    public char getIat() {
        return this.iat;
    }
    
    public void setIat(char iat) {
        this.iat = iat;
    }
    public char getIppt() {
        return this.ippt;
    }
    
    public void setIppt(char ippt) {
        this.ippt = ippt;
    }
    public int getCasasQnt() {
        return this.casasQnt;
    }
    
    public void setCasasQnt(int casasQnt) {
        this.casasQnt = casasQnt;
    }
    public int getCasasValor() {
        return this.casasValor;
    }
    
    public void setCasasValor(int casasValor) {
        this.casasValor = casasValor;
    }




}


