package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:19:07 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * PafRegR03 generated by hbm2java
 */
public class PafRegR03  implements java.io.Serializable {


     private int id;
     private String numeroFabricacao;
     private char mfAdicional;
     private String modeloEcf;
     private int numeroUsuario;
     private int crz;
     private String totalizadorParcial;
     private BigDecimal valor;

    public PafRegR03() {
    }

    public PafRegR03(int id, String numeroFabricacao, char mfAdicional, String modeloEcf, int numeroUsuario, int crz, String totalizadorParcial, BigDecimal valor) {
       this.id = id;
       this.numeroFabricacao = numeroFabricacao;
       this.mfAdicional = mfAdicional;
       this.modeloEcf = modeloEcf;
       this.numeroUsuario = numeroUsuario;
       this.crz = crz;
       this.totalizadorParcial = totalizadorParcial;
       this.valor = valor;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNumeroFabricacao() {
        return this.numeroFabricacao;
    }
    
    public void setNumeroFabricacao(String numeroFabricacao) {
        this.numeroFabricacao = numeroFabricacao;
    }
    public char getMfAdicional() {
        return this.mfAdicional;
    }
    
    public void setMfAdicional(char mfAdicional) {
        this.mfAdicional = mfAdicional;
    }
    public String getModeloEcf() {
        return this.modeloEcf;
    }
    
    public void setModeloEcf(String modeloEcf) {
        this.modeloEcf = modeloEcf;
    }
    public int getNumeroUsuario() {
        return this.numeroUsuario;
    }
    
    public void setNumeroUsuario(int numeroUsuario) {
        this.numeroUsuario = numeroUsuario;
    }
    public int getCrz() {
        return this.crz;
    }
    
    public void setCrz(int crz) {
        this.crz = crz;
    }
    public String getTotalizadorParcial() {
        return this.totalizadorParcial;
    }
    
    public void setTotalizadorParcial(String totalizadorParcial) {
        this.totalizadorParcial = totalizadorParcial;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


