package br.com.sinetic.pafecftef.entities;
// Generated 11-Mar-2013 10:11:53 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PafRegR06 generated by hbm2java
 */
public class PafRegR06  implements java.io.Serializable {


     private int id;
     private String numeroFabricacao;
     private char mfAdicional;
     private String modeloEcf;
     private int numeroUsuario;
     private int coo;
     private int gnf;
     private int grg;
     private int cdc;
     private String denominacao;
     private Date dataHora;

    public PafRegR06() {
    }

    public PafRegR06(int id, String numeroFabricacao, char mfAdicional, String modeloEcf, int numeroUsuario, int coo, int gnf, int grg, int cdc, String denominacao, Date dataHora) {
       this.id = id;
       this.numeroFabricacao = numeroFabricacao;
       this.mfAdicional = mfAdicional;
       this.modeloEcf = modeloEcf;
       this.numeroUsuario = numeroUsuario;
       this.coo = coo;
       this.gnf = gnf;
       this.grg = grg;
       this.cdc = cdc;
       this.denominacao = denominacao;
       this.dataHora = dataHora;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNumeroFabricacao() {
        return this.numeroFabricacao;
    }
    
    public void setNumeroFabricacao(String numeroFabricacao) {
        this.numeroFabricacao = numeroFabricacao;
    }
    public char getMfAdicional() {
        return this.mfAdicional;
    }
    
    public void setMfAdicional(char mfAdicional) {
        this.mfAdicional = mfAdicional;
    }
    public String getModeloEcf() {
        return this.modeloEcf;
    }
    
    public void setModeloEcf(String modeloEcf) {
        this.modeloEcf = modeloEcf;
    }
    public int getNumeroUsuario() {
        return this.numeroUsuario;
    }
    
    public void setNumeroUsuario(int numeroUsuario) {
        this.numeroUsuario = numeroUsuario;
    }
    public int getCoo() {
        return this.coo;
    }
    
    public void setCoo(int coo) {
        this.coo = coo;
    }
    public int getGnf() {
        return this.gnf;
    }
    
    public void setGnf(int gnf) {
        this.gnf = gnf;
    }
    public int getGrg() {
        return this.grg;
    }
    
    public void setGrg(int grg) {
        this.grg = grg;
    }
    public int getCdc() {
        return this.cdc;
    }
    
    public void setCdc(int cdc) {
        this.cdc = cdc;
    }
    public String getDenominacao() {
        return this.denominacao;
    }
    
    public void setDenominacao(String denominacao) {
        this.denominacao = denominacao;
    }
    public Date getDataHora() {
        return this.dataHora;
    }
    
    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }




}


