package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:19:07 by Hibernate Tools 3.2.1.GA



/**
 * PrevendaAberta generated by hbm2java
 */
public class PrevendaAberta  implements java.io.Serializable {


     private int id;
     private int fkBrPrevendaId;
     private int status;

    public PrevendaAberta() {
    }

    public PrevendaAberta(int id, int fkBrPrevendaId, int status) {
       this.id = id;
       this.fkBrPrevendaId = fkBrPrevendaId;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getFkBrPrevendaId() {
        return this.fkBrPrevendaId;
    }
    
    public void setFkBrPrevendaId(int fkBrPrevendaId) {
        this.fkBrPrevendaId = fkBrPrevendaId;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


