package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:50:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumento generated by hbm2java
 */
public class TipoDocumento  implements java.io.Serializable {


     private int id;
     private String nome;
     private Set pafMeiosPagamentoDias = new HashSet(0);

    public TipoDocumento() {
    }

	
    public TipoDocumento(int id, String nome) {
        this.id = id;
        this.nome = nome;
    }
    public TipoDocumento(int id, String nome, Set pafMeiosPagamentoDias) {
       this.id = id;
       this.nome = nome;
       this.pafMeiosPagamentoDias = pafMeiosPagamentoDias;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getPafMeiosPagamentoDias() {
        return this.pafMeiosPagamentoDias;
    }
    
    public void setPafMeiosPagamentoDias(Set pafMeiosPagamentoDias) {
        this.pafMeiosPagamentoDias = pafMeiosPagamentoDias;
    }




}


