package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:19:07 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * VendaPagamento generated by hbm2java
 */
public class VendaPagamento  implements java.io.Serializable {


     private int id;
     private int fkBrCodigoPreVenda;
     private BigDecimal valor;
     private boolean status;
     private int fkBrCodigoPagDetalhado;

    public VendaPagamento() {
    }

    public VendaPagamento(int id, int fkBrCodigoPreVenda, BigDecimal valor, boolean status, int fkBrCodigoPagDetalhado) {
       this.id = id;
       this.fkBrCodigoPreVenda = fkBrCodigoPreVenda;
       this.valor = valor;
       this.status = status;
       this.fkBrCodigoPagDetalhado = fkBrCodigoPagDetalhado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getFkBrCodigoPreVenda() {
        return this.fkBrCodigoPreVenda;
    }
    
    public void setFkBrCodigoPreVenda(int fkBrCodigoPreVenda) {
        this.fkBrCodigoPreVenda = fkBrCodigoPreVenda;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public int getFkBrCodigoPagDetalhado() {
        return this.fkBrCodigoPagDetalhado;
    }
    
    public void setFkBrCodigoPagDetalhado(int fkBrCodigoPagDetalhado) {
        this.fkBrCodigoPagDetalhado = fkBrCodigoPagDetalhado;
    }




}


