package br.com.sinetic.pafecftef.entities;
// Generated 03-Mar-2013 18:19:07 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Vendas generated by hbm2java
 */
public class Vendas  implements java.io.Serializable {


     private int id;
     private EcfComprador ecfComprador;
     private Integer codigo;
     private String vendedor;
     private String descricao;
     private Integer status;
     private Set items = new HashSet(0);

    public Vendas() {
    }

	
    public Vendas(int id) {
        this.id = id;
    }
    public Vendas(int id, EcfComprador ecfComprador, Integer codigo, String vendedor, String descricao, Integer status, Set items) {
       this.id = id;
       this.ecfComprador = ecfComprador;
       this.codigo = codigo;
       this.vendedor = vendedor;
       this.descricao = descricao;
       this.status = status;
       this.items = items;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public EcfComprador getEcfComprador() {
        return this.ecfComprador;
    }
    
    public void setEcfComprador(EcfComprador ecfComprador) {
        this.ecfComprador = ecfComprador;
    }
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(String vendedor) {
        this.vendedor = vendedor;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


