package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CrediarioFuncoes generated by hbm2java
 */
public class CrediarioFuncoes  implements java.io.Serializable {


     private int codigo;
     private String funcao;
     private String descricao;
     private Boolean status;
     private Set crediarioClientesForFuncaoConjuge = new HashSet(0);
     private Set crediarioClientesForFuncao = new HashSet(0);

    public CrediarioFuncoes() {
    }

	
    public CrediarioFuncoes(int codigo, String funcao) {
        this.codigo = codigo;
        this.funcao = funcao;
    }
    public CrediarioFuncoes(int codigo, String funcao, String descricao, Boolean status, Set crediarioClientesForFuncaoConjuge, Set crediarioClientesForFuncao) {
       this.codigo = codigo;
       this.funcao = funcao;
       this.descricao = descricao;
       this.status = status;
       this.crediarioClientesForFuncaoConjuge = crediarioClientesForFuncaoConjuge;
       this.crediarioClientesForFuncao = crediarioClientesForFuncao;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getFuncao() {
        return this.funcao;
    }
    
    public void setFuncao(String funcao) {
        this.funcao = funcao;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getCrediarioClientesForFuncaoConjuge() {
        return this.crediarioClientesForFuncaoConjuge;
    }
    
    public void setCrediarioClientesForFuncaoConjuge(Set crediarioClientesForFuncaoConjuge) {
        this.crediarioClientesForFuncaoConjuge = crediarioClientesForFuncaoConjuge;
    }
    public Set getCrediarioClientesForFuncao() {
        return this.crediarioClientesForFuncao;
    }
    
    public void setCrediarioClientesForFuncao(Set crediarioClientesForFuncao) {
        this.crediarioClientesForFuncao = crediarioClientesForFuncao;
    }




}


