package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CrediarioSetoresAtividade generated by hbm2java
 */
public class CrediarioSetoresAtividade  implements java.io.Serializable {


     private int codigo;
     private String setor;
     private String descricao;
     private Boolean status;
     private Set crediarioClientesForSetorAtividadeConjuge = new HashSet(0);
     private Set crediarioClientesForSetorAtividade = new HashSet(0);

    public CrediarioSetoresAtividade() {
    }

	
    public CrediarioSetoresAtividade(int codigo, String setor) {
        this.codigo = codigo;
        this.setor = setor;
    }
    public CrediarioSetoresAtividade(int codigo, String setor, String descricao, Boolean status, Set crediarioClientesForSetorAtividadeConjuge, Set crediarioClientesForSetorAtividade) {
       this.codigo = codigo;
       this.setor = setor;
       this.descricao = descricao;
       this.status = status;
       this.crediarioClientesForSetorAtividadeConjuge = crediarioClientesForSetorAtividadeConjuge;
       this.crediarioClientesForSetorAtividade = crediarioClientesForSetorAtividade;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getSetor() {
        return this.setor;
    }
    
    public void setSetor(String setor) {
        this.setor = setor;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getCrediarioClientesForSetorAtividadeConjuge() {
        return this.crediarioClientesForSetorAtividadeConjuge;
    }
    
    public void setCrediarioClientesForSetorAtividadeConjuge(Set crediarioClientesForSetorAtividadeConjuge) {
        this.crediarioClientesForSetorAtividadeConjuge = crediarioClientesForSetorAtividadeConjuge;
    }
    public Set getCrediarioClientesForSetorAtividade() {
        return this.crediarioClientesForSetorAtividade;
    }
    
    public void setCrediarioClientesForSetorAtividade(Set crediarioClientesForSetorAtividade) {
        this.crediarioClientesForSetorAtividade = crediarioClientesForSetorAtividade;
    }




}


