package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CrediarioObservacoes generated by hbm2java
 */
public class CrediarioObservacoes  implements java.io.Serializable {


     private int codigo;
     private String observacao;
     private Boolean status;
     private Set crediarioClientes = new HashSet(0);

    public CrediarioObservacoes() {
    }

	
    public CrediarioObservacoes(int codigo) {
        this.codigo = codigo;
    }
    public CrediarioObservacoes(int codigo, String observacao, Boolean status, Set crediarioClientes) {
       this.codigo = codigo;
       this.observacao = observacao;
       this.status = status;
       this.crediarioClientes = crediarioClientes;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getCrediarioClientes() {
        return this.crediarioClientes;
    }
    
    public void setCrediarioClientes(Set crediarioClientes) {
        this.crediarioClientes = crediarioClientes;
    }




}


