package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CrediarioFormaPagamentoDetalhado generated by hbm2java
 */
public class CrediarioFormaPagamentoDetalhado  implements java.io.Serializable {


     private int codigo;
     private CrediarioFormaPagamentoBandeira crediarioFormaPagamentoBandeira;
     private CrediarioFormaPagamento crediarioFormaPagamento;
     private CrediarioFormaPagamentoOperadora crediarioFormaPagamentoOperadora;
     private String nome;
     private Short numeroMaximoParcelas;
     private Float clienteDescontoAm;
     private Float clienteJurosAm;
     private String banco;
     private String bancoAgencia;
     private String bancoContaCorrente;
     private BigDecimal taxaAdministracao;
     private Character taxaAdministracaoTipo;
     private Short preferencia;
     private Short prazoRecebimento;
     private boolean status;
     private String tefApi;
     private Set crediarioVendaPagamentos = new HashSet(0);
     private Set crediarioVendaParcelamentos = new HashSet(0);
     private Set lojaFormaPagamentos = new HashSet(0);

    public CrediarioFormaPagamentoDetalhado() {
    }

	
    public CrediarioFormaPagamentoDetalhado(int codigo, CrediarioFormaPagamento crediarioFormaPagamento, String nome, boolean status) {
        this.codigo = codigo;
        this.crediarioFormaPagamento = crediarioFormaPagamento;
        this.nome = nome;
        this.status = status;
    }
    public CrediarioFormaPagamentoDetalhado(int codigo, CrediarioFormaPagamentoBandeira crediarioFormaPagamentoBandeira, CrediarioFormaPagamento crediarioFormaPagamento, CrediarioFormaPagamentoOperadora crediarioFormaPagamentoOperadora, String nome, Short numeroMaximoParcelas, Float clienteDescontoAm, Float clienteJurosAm, String banco, String bancoAgencia, String bancoContaCorrente, BigDecimal taxaAdministracao, Character taxaAdministracaoTipo, Short preferencia, Short prazoRecebimento, boolean status, String tefApi, Set crediarioVendaPagamentos, Set crediarioVendaParcelamentos, Set lojaFormaPagamentos) {
       this.codigo = codigo;
       this.crediarioFormaPagamentoBandeira = crediarioFormaPagamentoBandeira;
       this.crediarioFormaPagamento = crediarioFormaPagamento;
       this.crediarioFormaPagamentoOperadora = crediarioFormaPagamentoOperadora;
       this.nome = nome;
       this.numeroMaximoParcelas = numeroMaximoParcelas;
       this.clienteDescontoAm = clienteDescontoAm;
       this.clienteJurosAm = clienteJurosAm;
       this.banco = banco;
       this.bancoAgencia = bancoAgencia;
       this.bancoContaCorrente = bancoContaCorrente;
       this.taxaAdministracao = taxaAdministracao;
       this.taxaAdministracaoTipo = taxaAdministracaoTipo;
       this.preferencia = preferencia;
       this.prazoRecebimento = prazoRecebimento;
       this.status = status;
       this.tefApi = tefApi;
       this.crediarioVendaPagamentos = crediarioVendaPagamentos;
       this.crediarioVendaParcelamentos = crediarioVendaParcelamentos;
       this.lojaFormaPagamentos = lojaFormaPagamentos;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public CrediarioFormaPagamentoBandeira getCrediarioFormaPagamentoBandeira() {
        return this.crediarioFormaPagamentoBandeira;
    }
    
    public void setCrediarioFormaPagamentoBandeira(CrediarioFormaPagamentoBandeira crediarioFormaPagamentoBandeira) {
        this.crediarioFormaPagamentoBandeira = crediarioFormaPagamentoBandeira;
    }
    public CrediarioFormaPagamento getCrediarioFormaPagamento() {
        return this.crediarioFormaPagamento;
    }
    
    public void setCrediarioFormaPagamento(CrediarioFormaPagamento crediarioFormaPagamento) {
        this.crediarioFormaPagamento = crediarioFormaPagamento;
    }
    public CrediarioFormaPagamentoOperadora getCrediarioFormaPagamentoOperadora() {
        return this.crediarioFormaPagamentoOperadora;
    }
    
    public void setCrediarioFormaPagamentoOperadora(CrediarioFormaPagamentoOperadora crediarioFormaPagamentoOperadora) {
        this.crediarioFormaPagamentoOperadora = crediarioFormaPagamentoOperadora;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Short getNumeroMaximoParcelas() {
        return this.numeroMaximoParcelas;
    }
    
    public void setNumeroMaximoParcelas(Short numeroMaximoParcelas) {
        this.numeroMaximoParcelas = numeroMaximoParcelas;
    }
    public Float getClienteDescontoAm() {
        return this.clienteDescontoAm;
    }
    
    public void setClienteDescontoAm(Float clienteDescontoAm) {
        this.clienteDescontoAm = clienteDescontoAm;
    }
    public Float getClienteJurosAm() {
        return this.clienteJurosAm;
    }
    
    public void setClienteJurosAm(Float clienteJurosAm) {
        this.clienteJurosAm = clienteJurosAm;
    }
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }
    public String getBancoAgencia() {
        return this.bancoAgencia;
    }
    
    public void setBancoAgencia(String bancoAgencia) {
        this.bancoAgencia = bancoAgencia;
    }
    public String getBancoContaCorrente() {
        return this.bancoContaCorrente;
    }
    
    public void setBancoContaCorrente(String bancoContaCorrente) {
        this.bancoContaCorrente = bancoContaCorrente;
    }
    public BigDecimal getTaxaAdministracao() {
        return this.taxaAdministracao;
    }
    
    public void setTaxaAdministracao(BigDecimal taxaAdministracao) {
        this.taxaAdministracao = taxaAdministracao;
    }
    public Character getTaxaAdministracaoTipo() {
        return this.taxaAdministracaoTipo;
    }
    
    public void setTaxaAdministracaoTipo(Character taxaAdministracaoTipo) {
        this.taxaAdministracaoTipo = taxaAdministracaoTipo;
    }
    public Short getPreferencia() {
        return this.preferencia;
    }
    
    public void setPreferencia(Short preferencia) {
        this.preferencia = preferencia;
    }
    public Short getPrazoRecebimento() {
        return this.prazoRecebimento;
    }
    
    public void setPrazoRecebimento(Short prazoRecebimento) {
        this.prazoRecebimento = prazoRecebimento;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public String getTefApi() {
        return this.tefApi;
    }
    
    public void setTefApi(String tefApi) {
        this.tefApi = tefApi;
    }
    public Set getCrediarioVendaPagamentos() {
        return this.crediarioVendaPagamentos;
    }
    
    public void setCrediarioVendaPagamentos(Set crediarioVendaPagamentos) {
        this.crediarioVendaPagamentos = crediarioVendaPagamentos;
    }
    public Set getCrediarioVendaParcelamentos() {
        return this.crediarioVendaParcelamentos;
    }
    
    public void setCrediarioVendaParcelamentos(Set crediarioVendaParcelamentos) {
        this.crediarioVendaParcelamentos = crediarioVendaParcelamentos;
    }
    public Set getLojaFormaPagamentos() {
        return this.lojaFormaPagamentos;
    }
    
    public void setLojaFormaPagamentos(Set lojaFormaPagamentos) {
        this.lojaFormaPagamentos = lojaFormaPagamentos;
    }




}


