package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CrediarioTiposStatusPrestacao generated by hbm2java
 */
public class CrediarioTiposStatusPrestacao  implements java.io.Serializable {


     private short codigo;
     private String statusPrestacao;
     private Boolean status;
     private Set crediarioVendaParcelamentos = new HashSet(0);

    public CrediarioTiposStatusPrestacao() {
    }

	
    public CrediarioTiposStatusPrestacao(short codigo) {
        this.codigo = codigo;
    }
    public CrediarioTiposStatusPrestacao(short codigo, String statusPrestacao, Boolean status, Set crediarioVendaParcelamentos) {
       this.codigo = codigo;
       this.statusPrestacao = statusPrestacao;
       this.status = status;
       this.crediarioVendaParcelamentos = crediarioVendaParcelamentos;
    }
   
    public short getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(short codigo) {
        this.codigo = codigo;
    }
    public String getStatusPrestacao() {
        return this.statusPrestacao;
    }
    
    public void setStatusPrestacao(String statusPrestacao) {
        this.statusPrestacao = statusPrestacao;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getCrediarioVendaParcelamentos() {
        return this.crediarioVendaParcelamentos;
    }
    
    public void setCrediarioVendaParcelamentos(Set crediarioVendaParcelamentos) {
        this.crediarioVendaParcelamentos = crediarioVendaParcelamentos;
    }




}


