package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CrediarioRamosAtividade generated by hbm2java
 */
public class CrediarioRamosAtividade  implements java.io.Serializable {


     private int codigo;
     private String ramo;
     private String descricao;
     private Boolean status;
     private Set crediarioClientesForRamoAtividade = new HashSet(0);
     private Set crediarioClientesForRamoAtividadeConjuge = new HashSet(0);

    public CrediarioRamosAtividade() {
    }

	
    public CrediarioRamosAtividade(int codigo, String ramo) {
        this.codigo = codigo;
        this.ramo = ramo;
    }
    public CrediarioRamosAtividade(int codigo, String ramo, String descricao, Boolean status, Set crediarioClientesForRamoAtividade, Set crediarioClientesForRamoAtividadeConjuge) {
       this.codigo = codigo;
       this.ramo = ramo;
       this.descricao = descricao;
       this.status = status;
       this.crediarioClientesForRamoAtividade = crediarioClientesForRamoAtividade;
       this.crediarioClientesForRamoAtividadeConjuge = crediarioClientesForRamoAtividadeConjuge;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getRamo() {
        return this.ramo;
    }
    
    public void setRamo(String ramo) {
        this.ramo = ramo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getCrediarioClientesForRamoAtividade() {
        return this.crediarioClientesForRamoAtividade;
    }
    
    public void setCrediarioClientesForRamoAtividade(Set crediarioClientesForRamoAtividade) {
        this.crediarioClientesForRamoAtividade = crediarioClientesForRamoAtividade;
    }
    public Set getCrediarioClientesForRamoAtividadeConjuge() {
        return this.crediarioClientesForRamoAtividadeConjuge;
    }
    
    public void setCrediarioClientesForRamoAtividadeConjuge(Set crediarioClientesForRamoAtividadeConjuge) {
        this.crediarioClientesForRamoAtividadeConjuge = crediarioClientesForRamoAtividadeConjuge;
    }




}


