package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CrediarioFormaPagamentoBandeira generated by hbm2java
 */
public class CrediarioFormaPagamentoBandeira  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private String imagem;
     private boolean status;
     private Set crediarioFormaPagamentoDetalhados = new HashSet(0);

    public CrediarioFormaPagamentoBandeira() {
    }

	
    public CrediarioFormaPagamentoBandeira(int codigo, boolean status) {
        this.codigo = codigo;
        this.status = status;
    }
    public CrediarioFormaPagamentoBandeira(int codigo, String nome, String imagem, boolean status, Set crediarioFormaPagamentoDetalhados) {
       this.codigo = codigo;
       this.nome = nome;
       this.imagem = imagem;
       this.status = status;
       this.crediarioFormaPagamentoDetalhados = crediarioFormaPagamentoDetalhados;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getImagem() {
        return this.imagem;
    }
    
    public void setImagem(String imagem) {
        this.imagem = imagem;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getCrediarioFormaPagamentoDetalhados() {
        return this.crediarioFormaPagamentoDetalhados;
    }
    
    public void setCrediarioFormaPagamentoDetalhados(Set crediarioFormaPagamentoDetalhados) {
        this.crediarioFormaPagamentoDetalhados = crediarioFormaPagamentoDetalhados;
    }




}


