package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * FornecedoresRelacoesComerciais generated by hbm2java
 */
public class FornecedoresRelacoesComerciais  implements java.io.Serializable {


     private int codigo;
     private String relacao;
     private Short tipoRelacao;
     private Boolean status;
     private Set fornecedoreses = new HashSet(0);

    public FornecedoresRelacoesComerciais() {
    }

	
    public FornecedoresRelacoesComerciais(int codigo) {
        this.codigo = codigo;
    }
    public FornecedoresRelacoesComerciais(int codigo, String relacao, Short tipoRelacao, Boolean status, Set fornecedoreses) {
       this.codigo = codigo;
       this.relacao = relacao;
       this.tipoRelacao = tipoRelacao;
       this.status = status;
       this.fornecedoreses = fornecedoreses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getRelacao() {
        return this.relacao;
    }
    
    public void setRelacao(String relacao) {
        this.relacao = relacao;
    }
    public Short getTipoRelacao() {
        return this.tipoRelacao;
    }
    
    public void setTipoRelacao(Short tipoRelacao) {
        this.tipoRelacao = tipoRelacao;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getFornecedoreses() {
        return this.fornecedoreses;
    }
    
    public void setFornecedoreses(Set fornecedoreses) {
        this.fornecedoreses = fornecedoreses;
    }




}


