package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * FornecedoresRamosAtividades generated by hbm2java
 */
public class FornecedoresRamosAtividades  implements java.io.Serializable {


     private int codigo;
     private String ramo;
     private Short tipoRelacao;
     private Boolean status;
     private Set fornecedoreses = new HashSet(0);

    public FornecedoresRamosAtividades() {
    }

	
    public FornecedoresRamosAtividades(int codigo) {
        this.codigo = codigo;
    }
    public FornecedoresRamosAtividades(int codigo, String ramo, Short tipoRelacao, Boolean status, Set fornecedoreses) {
       this.codigo = codigo;
       this.ramo = ramo;
       this.tipoRelacao = tipoRelacao;
       this.status = status;
       this.fornecedoreses = fornecedoreses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getRamo() {
        return this.ramo;
    }
    
    public void setRamo(String ramo) {
        this.ramo = ramo;
    }
    public Short getTipoRelacao() {
        return this.tipoRelacao;
    }
    
    public void setTipoRelacao(Short tipoRelacao) {
        this.tipoRelacao = tipoRelacao;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getFornecedoreses() {
        return this.fornecedoreses;
    }
    
    public void setFornecedoreses(Set fornecedoreses) {
        this.fornecedoreses = fornecedoreses;
    }




}


