package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Loja generated by hbm2java
 */
public class Loja  implements java.io.Serializable {


     private short numero;
     private Regiao regiao;
     private String nome;
     private String cidade;
     private String endRua;
     private Short endNumero;
     private String endComplemento;
     private Boolean status;
     private String tipo;
     private String web;
     private String cep;
     private String cnpj;
     private String ie;
     private String endEstado;
     private String telefone;
     private Float jurosDia;
     private Float descontoDia;
     private BigDecimal peoPdv;
     private Float descontoRelativoPdv;
     private BigDecimal descontoAbsolutoPdv;
     private Set lojaFormaPagamentos = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set crediarioClientes = new HashSet(0);
     private Set preVendas = new HashSet(0);

    public Loja() {
    }

	
    public Loja(short numero) {
        this.numero = numero;
    }
    public Loja(short numero, Regiao regiao, String nome, String cidade, String endRua, Short endNumero, String endComplemento, Boolean status, String tipo, String web, String cep, String cnpj, String ie, String endEstado, String telefone, Float jurosDia, Float descontoDia, BigDecimal peoPdv, Float descontoRelativoPdv, BigDecimal descontoAbsolutoPdv, Set lojaFormaPagamentos, Set usuarios, Set crediarioClientes, Set preVendas) {
       this.numero = numero;
       this.regiao = regiao;
       this.nome = nome;
       this.cidade = cidade;
       this.endRua = endRua;
       this.endNumero = endNumero;
       this.endComplemento = endComplemento;
       this.status = status;
       this.tipo = tipo;
       this.web = web;
       this.cep = cep;
       this.cnpj = cnpj;
       this.ie = ie;
       this.endEstado = endEstado;
       this.telefone = telefone;
       this.jurosDia = jurosDia;
       this.descontoDia = descontoDia;
       this.peoPdv = peoPdv;
       this.descontoRelativoPdv = descontoRelativoPdv;
       this.descontoAbsolutoPdv = descontoAbsolutoPdv;
       this.lojaFormaPagamentos = lojaFormaPagamentos;
       this.usuarios = usuarios;
       this.crediarioClientes = crediarioClientes;
       this.preVendas = preVendas;
    }
   
    public short getNumero() {
        return this.numero;
    }
    
    public void setNumero(short numero) {
        this.numero = numero;
    }
    public Regiao getRegiao() {
        return this.regiao;
    }
    
    public void setRegiao(Regiao regiao) {
        this.regiao = regiao;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getEndRua() {
        return this.endRua;
    }
    
    public void setEndRua(String endRua) {
        this.endRua = endRua;
    }
    public Short getEndNumero() {
        return this.endNumero;
    }
    
    public void setEndNumero(Short endNumero) {
        this.endNumero = endNumero;
    }
    public String getEndComplemento() {
        return this.endComplemento;
    }
    
    public void setEndComplemento(String endComplemento) {
        this.endComplemento = endComplemento;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getWeb() {
        return this.web;
    }
    
    public void setWeb(String web) {
        this.web = web;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getIe() {
        return this.ie;
    }
    
    public void setIe(String ie) {
        this.ie = ie;
    }
    public String getEndEstado() {
        return this.endEstado;
    }
    
    public void setEndEstado(String endEstado) {
        this.endEstado = endEstado;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public Float getJurosDia() {
        return this.jurosDia;
    }
    
    public void setJurosDia(Float jurosDia) {
        this.jurosDia = jurosDia;
    }
    public Float getDescontoDia() {
        return this.descontoDia;
    }
    
    public void setDescontoDia(Float descontoDia) {
        this.descontoDia = descontoDia;
    }
    public BigDecimal getPeoPdv() {
        return this.peoPdv;
    }
    
    public void setPeoPdv(BigDecimal peoPdv) {
        this.peoPdv = peoPdv;
    }
    public Float getDescontoRelativoPdv() {
        return this.descontoRelativoPdv;
    }
    
    public void setDescontoRelativoPdv(Float descontoRelativoPdv) {
        this.descontoRelativoPdv = descontoRelativoPdv;
    }
    public BigDecimal getDescontoAbsolutoPdv() {
        return this.descontoAbsolutoPdv;
    }
    
    public void setDescontoAbsolutoPdv(BigDecimal descontoAbsolutoPdv) {
        this.descontoAbsolutoPdv = descontoAbsolutoPdv;
    }
    public Set getLojaFormaPagamentos() {
        return this.lojaFormaPagamentos;
    }
    
    public void setLojaFormaPagamentos(Set lojaFormaPagamentos) {
        this.lojaFormaPagamentos = lojaFormaPagamentos;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getCrediarioClientes() {
        return this.crediarioClientes;
    }
    
    public void setCrediarioClientes(Set crediarioClientes) {
        this.crediarioClientes = crediarioClientes;
    }
    public Set getPreVendas() {
        return this.preVendas;
    }
    
    public void setPreVendas(Set preVendas) {
        this.preVendas = preVendas;
    }




}


