package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * PafEcfDescontoTipo generated by hbm2java
 */
public class PafEcfDescontoTipo  implements java.io.Serializable {


     private char sigla;
     private String nome;
     private Set preVendas = new HashSet(0);
     private Set preVendaServicos = new HashSet(0);
     private Set preVendaProdutos = new HashSet(0);

    public PafEcfDescontoTipo() {
    }

	
    public PafEcfDescontoTipo(char sigla, String nome) {
        this.sigla = sigla;
        this.nome = nome;
    }
    public PafEcfDescontoTipo(char sigla, String nome, Set preVendas, Set preVendaServicos, Set preVendaProdutos) {
       this.sigla = sigla;
       this.nome = nome;
       this.preVendas = preVendas;
       this.preVendaServicos = preVendaServicos;
       this.preVendaProdutos = preVendaProdutos;
    }
   
    public char getSigla() {
        return this.sigla;
    }
    
    public void setSigla(char sigla) {
        this.sigla = sigla;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getPreVendas() {
        return this.preVendas;
    }
    
    public void setPreVendas(Set preVendas) {
        this.preVendas = preVendas;
    }
    public Set getPreVendaServicos() {
        return this.preVendaServicos;
    }
    
    public void setPreVendaServicos(Set preVendaServicos) {
        this.preVendaServicos = preVendaServicos;
    }
    public Set getPreVendaProdutos() {
        return this.preVendaProdutos;
    }
    
    public void setPreVendaProdutos(Set preVendaProdutos) {
        this.preVendaProdutos = preVendaProdutos;
    }




}


