package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PreVenda generated by hbm2java
 */
public class PreVenda  implements java.io.Serializable {


     private int codigo;
     private PafEcfDescontoTipo pafEcfDescontoTipo;
     private CrediarioCliente crediarioCliente;
     private Usuario usuario;
     private Loja loja;
     private Date criadoEm;
     private Date finalizadoEm;
     private BigDecimal valorInicial;
     private BigDecimal descontoValor;
     private BigDecimal valorFinal;
     private boolean finalizada;
     private boolean emProgresso;
     private boolean cancelada;
     private String codigoEcfFinalizador;
     private Integer numeroNota;
     private Integer codigoMovimentacao;
     private String observacaoLivre;
     private boolean preVenda;
     private Set preVendaProdutoItems = new HashSet(0);
     private Set preVendaProdutos = new HashSet(0);
     private Set crediarioVendaPagamentos = new HashSet(0);
     private Set preVendaServicos = new HashSet(0);
     private Set crediarioVendaParcelamentos = new HashSet(0);

    public PreVenda() {
    }

	
    public PreVenda(int codigo, Loja loja, Date criadoEm, BigDecimal valorInicial, BigDecimal descontoValor, BigDecimal valorFinal, boolean finalizada, boolean emProgresso, boolean cancelada, boolean preVenda) {
        this.codigo = codigo;
        this.loja = loja;
        this.criadoEm = criadoEm;
        this.valorInicial = valorInicial;
        this.descontoValor = descontoValor;
        this.valorFinal = valorFinal;
        this.finalizada = finalizada;
        this.emProgresso = emProgresso;
        this.cancelada = cancelada;
        this.preVenda = preVenda;
    }
    public PreVenda(int codigo, PafEcfDescontoTipo pafEcfDescontoTipo, CrediarioCliente crediarioCliente, Usuario usuario, Loja loja, Date criadoEm, Date finalizadoEm, BigDecimal valorInicial, BigDecimal descontoValor, BigDecimal valorFinal, boolean finalizada, boolean emProgresso, boolean cancelada, String codigoEcfFinalizador, Integer numeroNota, Integer codigoMovimentacao, String observacaoLivre, boolean preVenda, Set preVendaProdutoItems, Set preVendaProdutos, Set crediarioVendaPagamentos, Set preVendaServicos, Set crediarioVendaParcelamentos) {
       this.codigo = codigo;
       this.pafEcfDescontoTipo = pafEcfDescontoTipo;
       this.crediarioCliente = crediarioCliente;
       this.usuario = usuario;
       this.loja = loja;
       this.criadoEm = criadoEm;
       this.finalizadoEm = finalizadoEm;
       this.valorInicial = valorInicial;
       this.descontoValor = descontoValor;
       this.valorFinal = valorFinal;
       this.finalizada = finalizada;
       this.emProgresso = emProgresso;
       this.cancelada = cancelada;
       this.codigoEcfFinalizador = codigoEcfFinalizador;
       this.numeroNota = numeroNota;
       this.codigoMovimentacao = codigoMovimentacao;
       this.observacaoLivre = observacaoLivre;
       this.preVenda = preVenda;
       this.preVendaProdutoItems = preVendaProdutoItems;
       this.preVendaProdutos = preVendaProdutos;
       this.crediarioVendaPagamentos = crediarioVendaPagamentos;
       this.preVendaServicos = preVendaServicos;
       this.crediarioVendaParcelamentos = crediarioVendaParcelamentos;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public PafEcfDescontoTipo getPafEcfDescontoTipo() {
        return this.pafEcfDescontoTipo;
    }
    
    public void setPafEcfDescontoTipo(PafEcfDescontoTipo pafEcfDescontoTipo) {
        this.pafEcfDescontoTipo = pafEcfDescontoTipo;
    }
    public CrediarioCliente getCrediarioCliente() {
        return this.crediarioCliente;
    }
    
    public void setCrediarioCliente(CrediarioCliente crediarioCliente) {
        this.crediarioCliente = crediarioCliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Loja getLoja() {
        return this.loja;
    }
    
    public void setLoja(Loja loja) {
        this.loja = loja;
    }
    public Date getCriadoEm() {
        return this.criadoEm;
    }
    
    public void setCriadoEm(Date criadoEm) {
        this.criadoEm = criadoEm;
    }
    public Date getFinalizadoEm() {
        return this.finalizadoEm;
    }
    
    public void setFinalizadoEm(Date finalizadoEm) {
        this.finalizadoEm = finalizadoEm;
    }
    public BigDecimal getValorInicial() {
        return this.valorInicial;
    }
    
    public void setValorInicial(BigDecimal valorInicial) {
        this.valorInicial = valorInicial;
    }
    public BigDecimal getDescontoValor() {
        return this.descontoValor;
    }
    
    public void setDescontoValor(BigDecimal descontoValor) {
        this.descontoValor = descontoValor;
    }
    public BigDecimal getValorFinal() {
        return this.valorFinal;
    }
    
    public void setValorFinal(BigDecimal valorFinal) {
        this.valorFinal = valorFinal;
    }
    public boolean isFinalizada() {
        return this.finalizada;
    }
    
    public void setFinalizada(boolean finalizada) {
        this.finalizada = finalizada;
    }
    public boolean isEmProgresso() {
        return this.emProgresso;
    }
    
    public void setEmProgresso(boolean emProgresso) {
        this.emProgresso = emProgresso;
    }
    public boolean isCancelada() {
        return this.cancelada;
    }
    
    public void setCancelada(boolean cancelada) {
        this.cancelada = cancelada;
    }
    public String getCodigoEcfFinalizador() {
        return this.codigoEcfFinalizador;
    }
    
    public void setCodigoEcfFinalizador(String codigoEcfFinalizador) {
        this.codigoEcfFinalizador = codigoEcfFinalizador;
    }
    public Integer getNumeroNota() {
        return this.numeroNota;
    }
    
    public void setNumeroNota(Integer numeroNota) {
        this.numeroNota = numeroNota;
    }
    public Integer getCodigoMovimentacao() {
        return this.codigoMovimentacao;
    }
    
    public void setCodigoMovimentacao(Integer codigoMovimentacao) {
        this.codigoMovimentacao = codigoMovimentacao;
    }
    public String getObservacaoLivre() {
        return this.observacaoLivre;
    }
    
    public void setObservacaoLivre(String observacaoLivre) {
        this.observacaoLivre = observacaoLivre;
    }
    public boolean isPreVenda() {
        return this.preVenda;
    }
    
    public void setPreVenda(boolean preVenda) {
        this.preVenda = preVenda;
    }
    public Set getPreVendaProdutoItems() {
        return this.preVendaProdutoItems;
    }
    
    public void setPreVendaProdutoItems(Set preVendaProdutoItems) {
        this.preVendaProdutoItems = preVendaProdutoItems;
    }
    public Set getPreVendaProdutos() {
        return this.preVendaProdutos;
    }
    
    public void setPreVendaProdutos(Set preVendaProdutos) {
        this.preVendaProdutos = preVendaProdutos;
    }
    public Set getCrediarioVendaPagamentos() {
        return this.crediarioVendaPagamentos;
    }
    
    public void setCrediarioVendaPagamentos(Set crediarioVendaPagamentos) {
        this.crediarioVendaPagamentos = crediarioVendaPagamentos;
    }
    public Set getPreVendaServicos() {
        return this.preVendaServicos;
    }
    
    public void setPreVendaServicos(Set preVendaServicos) {
        this.preVendaServicos = preVendaServicos;
    }
    public Set getCrediarioVendaParcelamentos() {
        return this.crediarioVendaParcelamentos;
    }
    
    public void setCrediarioVendaParcelamentos(Set crediarioVendaParcelamentos) {
        this.crediarioVendaParcelamentos = crediarioVendaParcelamentos;
    }




}


