package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PreVendaProduto generated by hbm2java
 */
public class PreVendaProduto  implements java.io.Serializable {


     private int codigo;
     private PafEcfDescontoTipo pafEcfDescontoTipo;
     private PreVenda preVenda;
     private SineticControleEstoque sineticControleEstoque;
     private int quantidade;
     private BigDecimal valorInicial;
     private BigDecimal descontoValor;
     private BigDecimal valorFinal;
     private boolean status;
     private Set preVendaProdutoItems = new HashSet(0);

    public PreVendaProduto() {
    }

	
    public PreVendaProduto(int codigo, int quantidade, BigDecimal valorInicial, BigDecimal descontoValor, BigDecimal valorFinal, boolean status) {
        this.codigo = codigo;
        this.quantidade = quantidade;
        this.valorInicial = valorInicial;
        this.descontoValor = descontoValor;
        this.valorFinal = valorFinal;
        this.status = status;
    }
    public PreVendaProduto(int codigo, PafEcfDescontoTipo pafEcfDescontoTipo, PreVenda preVenda, SineticControleEstoque sineticControleEstoque, int quantidade, BigDecimal valorInicial, BigDecimal descontoValor, BigDecimal valorFinal, boolean status, Set preVendaProdutoItems) {
       this.codigo = codigo;
       this.pafEcfDescontoTipo = pafEcfDescontoTipo;
       this.preVenda = preVenda;
       this.sineticControleEstoque = sineticControleEstoque;
       this.quantidade = quantidade;
       this.valorInicial = valorInicial;
       this.descontoValor = descontoValor;
       this.valorFinal = valorFinal;
       this.status = status;
       this.preVendaProdutoItems = preVendaProdutoItems;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public PafEcfDescontoTipo getPafEcfDescontoTipo() {
        return this.pafEcfDescontoTipo;
    }
    
    public void setPafEcfDescontoTipo(PafEcfDescontoTipo pafEcfDescontoTipo) {
        this.pafEcfDescontoTipo = pafEcfDescontoTipo;
    }
    public PreVenda getPreVenda() {
        return this.preVenda;
    }
    
    public void setPreVenda(PreVenda preVenda) {
        this.preVenda = preVenda;
    }
    public SineticControleEstoque getSineticControleEstoque() {
        return this.sineticControleEstoque;
    }
    
    public void setSineticControleEstoque(SineticControleEstoque sineticControleEstoque) {
        this.sineticControleEstoque = sineticControleEstoque;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public BigDecimal getValorInicial() {
        return this.valorInicial;
    }
    
    public void setValorInicial(BigDecimal valorInicial) {
        this.valorInicial = valorInicial;
    }
    public BigDecimal getDescontoValor() {
        return this.descontoValor;
    }
    
    public void setDescontoValor(BigDecimal descontoValor) {
        this.descontoValor = descontoValor;
    }
    public BigDecimal getValorFinal() {
        return this.valorFinal;
    }
    
    public void setValorFinal(BigDecimal valorFinal) {
        this.valorFinal = valorFinal;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getPreVendaProdutoItems() {
        return this.preVendaProdutoItems;
    }
    
    public void setPreVendaProdutoItems(Set preVendaProdutoItems) {
        this.preVendaProdutoItems = preVendaProdutoItems;
    }




}


