package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ProdutoGrupo generated by hbm2java
 */
public class ProdutoGrupo  implements java.io.Serializable {


     private int codigo;
     private String grupo;
     private Boolean status;
     private Set produtoses = new HashSet(0);
     private Set produtoSubgrupos = new HashSet(0);

    public ProdutoGrupo() {
    }

	
    public ProdutoGrupo(int codigo) {
        this.codigo = codigo;
    }
    public ProdutoGrupo(int codigo, String grupo, Boolean status, Set produtoses, Set produtoSubgrupos) {
       this.codigo = codigo;
       this.grupo = grupo;
       this.status = status;
       this.produtoses = produtoses;
       this.produtoSubgrupos = produtoSubgrupos;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getProdutoses() {
        return this.produtoses;
    }
    
    public void setProdutoses(Set produtoses) {
        this.produtoses = produtoses;
    }
    public Set getProdutoSubgrupos() {
        return this.produtoSubgrupos;
    }
    
    public void setProdutoSubgrupos(Set produtoSubgrupos) {
        this.produtoSubgrupos = produtoSubgrupos;
    }




}


