package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProdutoMarca generated by hbm2java
 */
public class ProdutoMarca  implements java.io.Serializable {


     private int codigo;
     private Usuario usuarioByCriadoPor;
     private Fornecedores fornecedores;
     private Usuario usuarioByAlteradoPor;
     private String nomeInterno;
     private String nomeExibicao;
     private BigDecimal margem;
     private BigDecimal markUpSugerido;
     private BigDecimal descontoNegociado;
     private Date criadoEm;
     private Date alteradoEm;
     private Boolean status;
     private Set produtoses = new HashSet(0);

    public ProdutoMarca() {
    }

	
    public ProdutoMarca(int codigo) {
        this.codigo = codigo;
    }
    public ProdutoMarca(int codigo, Usuario usuarioByCriadoPor, Fornecedores fornecedores, Usuario usuarioByAlteradoPor, String nomeInterno, String nomeExibicao, BigDecimal margem, BigDecimal markUpSugerido, BigDecimal descontoNegociado, Date criadoEm, Date alteradoEm, Boolean status, Set produtoses) {
       this.codigo = codigo;
       this.usuarioByCriadoPor = usuarioByCriadoPor;
       this.fornecedores = fornecedores;
       this.usuarioByAlteradoPor = usuarioByAlteradoPor;
       this.nomeInterno = nomeInterno;
       this.nomeExibicao = nomeExibicao;
       this.margem = margem;
       this.markUpSugerido = markUpSugerido;
       this.descontoNegociado = descontoNegociado;
       this.criadoEm = criadoEm;
       this.alteradoEm = alteradoEm;
       this.status = status;
       this.produtoses = produtoses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Usuario getUsuarioByCriadoPor() {
        return this.usuarioByCriadoPor;
    }
    
    public void setUsuarioByCriadoPor(Usuario usuarioByCriadoPor) {
        this.usuarioByCriadoPor = usuarioByCriadoPor;
    }
    public Fornecedores getFornecedores() {
        return this.fornecedores;
    }
    
    public void setFornecedores(Fornecedores fornecedores) {
        this.fornecedores = fornecedores;
    }
    public Usuario getUsuarioByAlteradoPor() {
        return this.usuarioByAlteradoPor;
    }
    
    public void setUsuarioByAlteradoPor(Usuario usuarioByAlteradoPor) {
        this.usuarioByAlteradoPor = usuarioByAlteradoPor;
    }
    public String getNomeInterno() {
        return this.nomeInterno;
    }
    
    public void setNomeInterno(String nomeInterno) {
        this.nomeInterno = nomeInterno;
    }
    public String getNomeExibicao() {
        return this.nomeExibicao;
    }
    
    public void setNomeExibicao(String nomeExibicao) {
        this.nomeExibicao = nomeExibicao;
    }
    public BigDecimal getMargem() {
        return this.margem;
    }
    
    public void setMargem(BigDecimal margem) {
        this.margem = margem;
    }
    public BigDecimal getMarkUpSugerido() {
        return this.markUpSugerido;
    }
    
    public void setMarkUpSugerido(BigDecimal markUpSugerido) {
        this.markUpSugerido = markUpSugerido;
    }
    public BigDecimal getDescontoNegociado() {
        return this.descontoNegociado;
    }
    
    public void setDescontoNegociado(BigDecimal descontoNegociado) {
        this.descontoNegociado = descontoNegociado;
    }
    public Date getCriadoEm() {
        return this.criadoEm;
    }
    
    public void setCriadoEm(Date criadoEm) {
        this.criadoEm = criadoEm;
    }
    public Date getAlteradoEm() {
        return this.alteradoEm;
    }
    
    public void setAlteradoEm(Date alteradoEm) {
        this.alteradoEm = alteradoEm;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getProdutoses() {
        return this.produtoses;
    }
    
    public void setProdutoses(Set produtoses) {
        this.produtoses = produtoses;
    }




}


