package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ProdutoSubgrupo generated by hbm2java
 */
public class ProdutoSubgrupo  implements java.io.Serializable {


     private int codigo;
     private ProdutoGrupo produtoGrupo;
     private String subgrupo;
     private String descricao;
     private Boolean status;
     private Set produtoses = new HashSet(0);

    public ProdutoSubgrupo() {
    }

	
    public ProdutoSubgrupo(int codigo) {
        this.codigo = codigo;
    }
    public ProdutoSubgrupo(int codigo, ProdutoGrupo produtoGrupo, String subgrupo, String descricao, Boolean status, Set produtoses) {
       this.codigo = codigo;
       this.produtoGrupo = produtoGrupo;
       this.subgrupo = subgrupo;
       this.descricao = descricao;
       this.status = status;
       this.produtoses = produtoses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public ProdutoGrupo getProdutoGrupo() {
        return this.produtoGrupo;
    }
    
    public void setProdutoGrupo(ProdutoGrupo produtoGrupo) {
        this.produtoGrupo = produtoGrupo;
    }
    public String getSubgrupo() {
        return this.subgrupo;
    }
    
    public void setSubgrupo(String subgrupo) {
        this.subgrupo = subgrupo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getProdutoses() {
        return this.produtoses;
    }
    
    public void setProdutoses(Set produtoses) {
        this.produtoses = produtoses;
    }




}


