package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Produtos generated by hbm2java
 */
public class Produtos  implements java.io.Serializable {


     private long codigo;
     private SineticProdutoModelo sineticProdutoModelo;
     private Usuario usuarioByCriadoPor;
     private ProdutoGrupo produtoGrupo;
     private CodigoUniversal codigoUniversal;
     private ProdutoMarca produtoMarca;
     private Fornecedores fornecedoresByCodFabricante;
     private Fornecedores fornecedoresByCodFornecedor;
     private ProdutoSubgrupo produtoSubgrupo;
     private Usuario usuarioByAlteradoPor;
     private long codReferencia;
     private String codBarras;
     private String codProdFornecedor;
     private String modelo;
     private String etiqueta1;
     private String etiqueta2;
     private String etiqueta3;
     private Date criadoEm;
     private Date alteradoEm;
     private Boolean status;
     private Set preVendaProdutoItems = new HashSet(0);

    public Produtos() {
    }

	
    public Produtos(long codigo, SineticProdutoModelo sineticProdutoModelo, ProdutoGrupo produtoGrupo, CodigoUniversal codigoUniversal, ProdutoMarca produtoMarca, ProdutoSubgrupo produtoSubgrupo, long codReferencia) {
        this.codigo = codigo;
        this.sineticProdutoModelo = sineticProdutoModelo;
        this.produtoGrupo = produtoGrupo;
        this.codigoUniversal = codigoUniversal;
        this.produtoMarca = produtoMarca;
        this.produtoSubgrupo = produtoSubgrupo;
        this.codReferencia = codReferencia;
    }
    public Produtos(long codigo, SineticProdutoModelo sineticProdutoModelo, Usuario usuarioByCriadoPor, ProdutoGrupo produtoGrupo, CodigoUniversal codigoUniversal, ProdutoMarca produtoMarca, Fornecedores fornecedoresByCodFabricante, Fornecedores fornecedoresByCodFornecedor, ProdutoSubgrupo produtoSubgrupo, Usuario usuarioByAlteradoPor, long codReferencia, String codBarras, String codProdFornecedor, String modelo, String etiqueta1, String etiqueta2, String etiqueta3, Date criadoEm, Date alteradoEm, Boolean status, Set preVendaProdutoItems) {
       this.codigo = codigo;
       this.sineticProdutoModelo = sineticProdutoModelo;
       this.usuarioByCriadoPor = usuarioByCriadoPor;
       this.produtoGrupo = produtoGrupo;
       this.codigoUniversal = codigoUniversal;
       this.produtoMarca = produtoMarca;
       this.fornecedoresByCodFabricante = fornecedoresByCodFabricante;
       this.fornecedoresByCodFornecedor = fornecedoresByCodFornecedor;
       this.produtoSubgrupo = produtoSubgrupo;
       this.usuarioByAlteradoPor = usuarioByAlteradoPor;
       this.codReferencia = codReferencia;
       this.codBarras = codBarras;
       this.codProdFornecedor = codProdFornecedor;
       this.modelo = modelo;
       this.etiqueta1 = etiqueta1;
       this.etiqueta2 = etiqueta2;
       this.etiqueta3 = etiqueta3;
       this.criadoEm = criadoEm;
       this.alteradoEm = alteradoEm;
       this.status = status;
       this.preVendaProdutoItems = preVendaProdutoItems;
    }
   
    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }
    public SineticProdutoModelo getSineticProdutoModelo() {
        return this.sineticProdutoModelo;
    }
    
    public void setSineticProdutoModelo(SineticProdutoModelo sineticProdutoModelo) {
        this.sineticProdutoModelo = sineticProdutoModelo;
    }
    public Usuario getUsuarioByCriadoPor() {
        return this.usuarioByCriadoPor;
    }
    
    public void setUsuarioByCriadoPor(Usuario usuarioByCriadoPor) {
        this.usuarioByCriadoPor = usuarioByCriadoPor;
    }
    public ProdutoGrupo getProdutoGrupo() {
        return this.produtoGrupo;
    }
    
    public void setProdutoGrupo(ProdutoGrupo produtoGrupo) {
        this.produtoGrupo = produtoGrupo;
    }
    public CodigoUniversal getCodigoUniversal() {
        return this.codigoUniversal;
    }
    
    public void setCodigoUniversal(CodigoUniversal codigoUniversal) {
        this.codigoUniversal = codigoUniversal;
    }
    public ProdutoMarca getProdutoMarca() {
        return this.produtoMarca;
    }
    
    public void setProdutoMarca(ProdutoMarca produtoMarca) {
        this.produtoMarca = produtoMarca;
    }
    public Fornecedores getFornecedoresByCodFabricante() {
        return this.fornecedoresByCodFabricante;
    }
    
    public void setFornecedoresByCodFabricante(Fornecedores fornecedoresByCodFabricante) {
        this.fornecedoresByCodFabricante = fornecedoresByCodFabricante;
    }
    public Fornecedores getFornecedoresByCodFornecedor() {
        return this.fornecedoresByCodFornecedor;
    }
    
    public void setFornecedoresByCodFornecedor(Fornecedores fornecedoresByCodFornecedor) {
        this.fornecedoresByCodFornecedor = fornecedoresByCodFornecedor;
    }
    public ProdutoSubgrupo getProdutoSubgrupo() {
        return this.produtoSubgrupo;
    }
    
    public void setProdutoSubgrupo(ProdutoSubgrupo produtoSubgrupo) {
        this.produtoSubgrupo = produtoSubgrupo;
    }
    public Usuario getUsuarioByAlteradoPor() {
        return this.usuarioByAlteradoPor;
    }
    
    public void setUsuarioByAlteradoPor(Usuario usuarioByAlteradoPor) {
        this.usuarioByAlteradoPor = usuarioByAlteradoPor;
    }
    public long getCodReferencia() {
        return this.codReferencia;
    }
    
    public void setCodReferencia(long codReferencia) {
        this.codReferencia = codReferencia;
    }
    public String getCodBarras() {
        return this.codBarras;
    }
    
    public void setCodBarras(String codBarras) {
        this.codBarras = codBarras;
    }
    public String getCodProdFornecedor() {
        return this.codProdFornecedor;
    }
    
    public void setCodProdFornecedor(String codProdFornecedor) {
        this.codProdFornecedor = codProdFornecedor;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getEtiqueta1() {
        return this.etiqueta1;
    }
    
    public void setEtiqueta1(String etiqueta1) {
        this.etiqueta1 = etiqueta1;
    }
    public String getEtiqueta2() {
        return this.etiqueta2;
    }
    
    public void setEtiqueta2(String etiqueta2) {
        this.etiqueta2 = etiqueta2;
    }
    public String getEtiqueta3() {
        return this.etiqueta3;
    }
    
    public void setEtiqueta3(String etiqueta3) {
        this.etiqueta3 = etiqueta3;
    }
    public Date getCriadoEm() {
        return this.criadoEm;
    }
    
    public void setCriadoEm(Date criadoEm) {
        this.criadoEm = criadoEm;
    }
    public Date getAlteradoEm() {
        return this.alteradoEm;
    }
    
    public void setAlteradoEm(Date alteradoEm) {
        this.alteradoEm = alteradoEm;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getPreVendaProdutoItems() {
        return this.preVendaProdutoItems;
    }
    
    public void setPreVendaProdutoItems(Set preVendaProdutoItems) {
        this.preVendaProdutoItems = preVendaProdutoItems;
    }




}


