package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Regiao generated by hbm2java
 */
public class Regiao  implements java.io.Serializable {


     private int codigo;
     private String regiao;
     private Boolean status;
     private Set lojas = new HashSet(0);

    public Regiao() {
    }

	
    public Regiao(int codigo) {
        this.codigo = codigo;
    }
    public Regiao(int codigo, String regiao, Boolean status, Set lojas) {
       this.codigo = codigo;
       this.regiao = regiao;
       this.status = status;
       this.lojas = lojas;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getRegiao() {
        return this.regiao;
    }
    
    public void setRegiao(String regiao) {
        this.regiao = regiao;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getLojas() {
        return this.lojas;
    }
    
    public void setLojas(Set lojas) {
        this.lojas = lojas;
    }




}


