package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Servico generated by hbm2java
 */
public class Servico  implements java.io.Serializable {


     private int codigo;
     private ServicoSubtipo servicoSubtipo;
     private Usuario usuarioByCriadoPor;
     private PafEcfProducao pafEcfProducao;
     private PafEcfSituacaoTributaria pafEcfSituacaoTributaria;
     private ServicoTipo servicoTipo;
     private PafEcfArredondamento pafEcfArredondamento;
     private Usuario usuarioByAlteradoPor;
     private PafEcfUnidadeMedida pafEcfUnidadeMedida;
     private String gtin;
     private String descricao;
     private BigDecimal valor;
     private Date criadoEm;
     private Date alteradoEm;
     private boolean status;
     private Set preVendaServicos = new HashSet(0);

    public Servico() {
    }

	
    public Servico(int codigo, ServicoSubtipo servicoSubtipo, PafEcfProducao pafEcfProducao, PafEcfSituacaoTributaria pafEcfSituacaoTributaria, ServicoTipo servicoTipo, PafEcfArredondamento pafEcfArredondamento, PafEcfUnidadeMedida pafEcfUnidadeMedida, String gtin, String descricao, BigDecimal valor, Date criadoEm, boolean status) {
        this.codigo = codigo;
        this.servicoSubtipo = servicoSubtipo;
        this.pafEcfProducao = pafEcfProducao;
        this.pafEcfSituacaoTributaria = pafEcfSituacaoTributaria;
        this.servicoTipo = servicoTipo;
        this.pafEcfArredondamento = pafEcfArredondamento;
        this.pafEcfUnidadeMedida = pafEcfUnidadeMedida;
        this.gtin = gtin;
        this.descricao = descricao;
        this.valor = valor;
        this.criadoEm = criadoEm;
        this.status = status;
    }
    public Servico(int codigo, ServicoSubtipo servicoSubtipo, Usuario usuarioByCriadoPor, PafEcfProducao pafEcfProducao, PafEcfSituacaoTributaria pafEcfSituacaoTributaria, ServicoTipo servicoTipo, PafEcfArredondamento pafEcfArredondamento, Usuario usuarioByAlteradoPor, PafEcfUnidadeMedida pafEcfUnidadeMedida, String gtin, String descricao, BigDecimal valor, Date criadoEm, Date alteradoEm, boolean status, Set preVendaServicos) {
       this.codigo = codigo;
       this.servicoSubtipo = servicoSubtipo;
       this.usuarioByCriadoPor = usuarioByCriadoPor;
       this.pafEcfProducao = pafEcfProducao;
       this.pafEcfSituacaoTributaria = pafEcfSituacaoTributaria;
       this.servicoTipo = servicoTipo;
       this.pafEcfArredondamento = pafEcfArredondamento;
       this.usuarioByAlteradoPor = usuarioByAlteradoPor;
       this.pafEcfUnidadeMedida = pafEcfUnidadeMedida;
       this.gtin = gtin;
       this.descricao = descricao;
       this.valor = valor;
       this.criadoEm = criadoEm;
       this.alteradoEm = alteradoEm;
       this.status = status;
       this.preVendaServicos = preVendaServicos;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public ServicoSubtipo getServicoSubtipo() {
        return this.servicoSubtipo;
    }
    
    public void setServicoSubtipo(ServicoSubtipo servicoSubtipo) {
        this.servicoSubtipo = servicoSubtipo;
    }
    public Usuario getUsuarioByCriadoPor() {
        return this.usuarioByCriadoPor;
    }
    
    public void setUsuarioByCriadoPor(Usuario usuarioByCriadoPor) {
        this.usuarioByCriadoPor = usuarioByCriadoPor;
    }
    public PafEcfProducao getPafEcfProducao() {
        return this.pafEcfProducao;
    }
    
    public void setPafEcfProducao(PafEcfProducao pafEcfProducao) {
        this.pafEcfProducao = pafEcfProducao;
    }
    public PafEcfSituacaoTributaria getPafEcfSituacaoTributaria() {
        return this.pafEcfSituacaoTributaria;
    }
    
    public void setPafEcfSituacaoTributaria(PafEcfSituacaoTributaria pafEcfSituacaoTributaria) {
        this.pafEcfSituacaoTributaria = pafEcfSituacaoTributaria;
    }
    public ServicoTipo getServicoTipo() {
        return this.servicoTipo;
    }
    
    public void setServicoTipo(ServicoTipo servicoTipo) {
        this.servicoTipo = servicoTipo;
    }
    public PafEcfArredondamento getPafEcfArredondamento() {
        return this.pafEcfArredondamento;
    }
    
    public void setPafEcfArredondamento(PafEcfArredondamento pafEcfArredondamento) {
        this.pafEcfArredondamento = pafEcfArredondamento;
    }
    public Usuario getUsuarioByAlteradoPor() {
        return this.usuarioByAlteradoPor;
    }
    
    public void setUsuarioByAlteradoPor(Usuario usuarioByAlteradoPor) {
        this.usuarioByAlteradoPor = usuarioByAlteradoPor;
    }
    public PafEcfUnidadeMedida getPafEcfUnidadeMedida() {
        return this.pafEcfUnidadeMedida;
    }
    
    public void setPafEcfUnidadeMedida(PafEcfUnidadeMedida pafEcfUnidadeMedida) {
        this.pafEcfUnidadeMedida = pafEcfUnidadeMedida;
    }
    public String getGtin() {
        return this.gtin;
    }
    
    public void setGtin(String gtin) {
        this.gtin = gtin;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public Date getCriadoEm() {
        return this.criadoEm;
    }
    
    public void setCriadoEm(Date criadoEm) {
        this.criadoEm = criadoEm;
    }
    public Date getAlteradoEm() {
        return this.alteradoEm;
    }
    
    public void setAlteradoEm(Date alteradoEm) {
        this.alteradoEm = alteradoEm;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getPreVendaServicos() {
        return this.preVendaServicos;
    }
    
    public void setPreVendaServicos(Set preVendaServicos) {
        this.preVendaServicos = preVendaServicos;
    }




}


