package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SineticControleEstoque generated by hbm2java
 */
public class SineticControleEstoque  implements java.io.Serializable {


     private int codigo;
     private PafEcfProducao pafEcfProducao;
     private PafEcfSituacaoTributaria pafEcfSituacaoTributaria;
     private PafEcfArredondamento pafEcfArredondamento;
     private PafEcfUnidadeMedida pafEcfUnidadeMedida;
     private int codigoProdutoReferencia;
     private int quantidade;
     private String gtin;
     private Set preVendaProdutos = new HashSet(0);

    public SineticControleEstoque() {
    }

	
    public SineticControleEstoque(int codigo, PafEcfProducao pafEcfProducao, PafEcfSituacaoTributaria pafEcfSituacaoTributaria, PafEcfArredondamento pafEcfArredondamento, PafEcfUnidadeMedida pafEcfUnidadeMedida, int codigoProdutoReferencia, int quantidade, String gtin) {
        this.codigo = codigo;
        this.pafEcfProducao = pafEcfProducao;
        this.pafEcfSituacaoTributaria = pafEcfSituacaoTributaria;
        this.pafEcfArredondamento = pafEcfArredondamento;
        this.pafEcfUnidadeMedida = pafEcfUnidadeMedida;
        this.codigoProdutoReferencia = codigoProdutoReferencia;
        this.quantidade = quantidade;
        this.gtin = gtin;
    }
    public SineticControleEstoque(int codigo, PafEcfProducao pafEcfProducao, PafEcfSituacaoTributaria pafEcfSituacaoTributaria, PafEcfArredondamento pafEcfArredondamento, PafEcfUnidadeMedida pafEcfUnidadeMedida, int codigoProdutoReferencia, int quantidade, String gtin, Set preVendaProdutos) {
       this.codigo = codigo;
       this.pafEcfProducao = pafEcfProducao;
       this.pafEcfSituacaoTributaria = pafEcfSituacaoTributaria;
       this.pafEcfArredondamento = pafEcfArredondamento;
       this.pafEcfUnidadeMedida = pafEcfUnidadeMedida;
       this.codigoProdutoReferencia = codigoProdutoReferencia;
       this.quantidade = quantidade;
       this.gtin = gtin;
       this.preVendaProdutos = preVendaProdutos;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public PafEcfProducao getPafEcfProducao() {
        return this.pafEcfProducao;
    }
    
    public void setPafEcfProducao(PafEcfProducao pafEcfProducao) {
        this.pafEcfProducao = pafEcfProducao;
    }
    public PafEcfSituacaoTributaria getPafEcfSituacaoTributaria() {
        return this.pafEcfSituacaoTributaria;
    }
    
    public void setPafEcfSituacaoTributaria(PafEcfSituacaoTributaria pafEcfSituacaoTributaria) {
        this.pafEcfSituacaoTributaria = pafEcfSituacaoTributaria;
    }
    public PafEcfArredondamento getPafEcfArredondamento() {
        return this.pafEcfArredondamento;
    }
    
    public void setPafEcfArredondamento(PafEcfArredondamento pafEcfArredondamento) {
        this.pafEcfArredondamento = pafEcfArredondamento;
    }
    public PafEcfUnidadeMedida getPafEcfUnidadeMedida() {
        return this.pafEcfUnidadeMedida;
    }
    
    public void setPafEcfUnidadeMedida(PafEcfUnidadeMedida pafEcfUnidadeMedida) {
        this.pafEcfUnidadeMedida = pafEcfUnidadeMedida;
    }
    public int getCodigoProdutoReferencia() {
        return this.codigoProdutoReferencia;
    }
    
    public void setCodigoProdutoReferencia(int codigoProdutoReferencia) {
        this.codigoProdutoReferencia = codigoProdutoReferencia;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public String getGtin() {
        return this.gtin;
    }
    
    public void setGtin(String gtin) {
        this.gtin = gtin;
    }
    public Set getPreVendaProdutos() {
        return this.preVendaProdutos;
    }
    
    public void setPreVendaProdutos(Set preVendaProdutos) {
        this.preVendaProdutos = preVendaProdutos;
    }




}


