package br.com.sinetic.pafecftef.remoteentities;
// Generated 05-Mar-2013 18:04:02 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private short codigo;
     private Usuario usuarioByAlteradoMultiploPor;
     private Usuario usuarioByCodigo;
     private GrupoUsuario grupoUsuario;
     private Loja loja;
     private String nome;
     private String apelido;
     private String senha;
     private Boolean status;
     private String email;
     private Date criadoEm;
     private Short criadoPor;
     private Date alteradoEm;
     private Short alteradoPor;
     private Short ramal;
     private Date dtNascimento;
     private String sexo;
     private String rg;
     private String rgEstExp;
     private String cpf;
     private String nomePai;
     private String nomeMae;
     private String nomeConjuge;
     private String estadoCivil;
     private Short NFilhos;
     private String nomeFilho1;
     private String nomeFilho2;
     private String nomeFilho3;
     private String nomeFilho4;
     private String nomeFilho5;
     private String escolaridade;
     private String escolaridadeNivel;
     private String endRua;
     private String endNumero;
     private String endComplemento;
     private String endBairro;
     private String endCidade;
     private String endCep;
     private String endEstado;
     private String telResidencial;
     private String telContato;
     private String nomeContato;
     private String telCelular;
     private Boolean alergico;
     private String tipoAlergia;
     private Boolean deveAlterarSenha;
     private Date ultimaAlteracaoSenha;
     private Boolean deveRecadastrar;
     private Date ultimoRecadastramento;
     private Boolean podeAlterarSenha;
     private Date alteradoMultiploEm;
     private short adiarRecadastramento;
     private String foto;
     private String observacoes;
     private Boolean superAdministrador;
     private Set usuariosForCodigo = new HashSet(0);
     private Set servicosForAlteradoPor = new HashSet(0);
     private Set usuariosForCodigo_1 = new HashSet(0);
     private Set usuariosForAlteradoMultiploPor = new HashSet(0);
     private Set produtosesForAlteradoPor = new HashSet(0);
     private Set crediarioClientesForModificadoPor = new HashSet(0);
     private Set lojaFormaPagamentos = new HashSet(0);
     private Set produtoMarcasForAlteradoPor = new HashSet(0);
     private Set crediarioClientesForCadastradoPor = new HashSet(0);
     private Set produtoMarcasForCriadoPor = new HashSet(0);
     private Set fornecedoresesForAdicionadoPor = new HashSet(0);
     private Set produtosesForCriadoPor = new HashSet(0);
     private Set servicosForCriadoPor = new HashSet(0);
     private Set fornecedoresesForModificadoPor = new HashSet(0);
     private Set preVendas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(short codigo, Usuario usuarioByCodigo, short adiarRecadastramento) {
        this.codigo = codigo;
        this.usuarioByCodigo = usuarioByCodigo;
        this.adiarRecadastramento = adiarRecadastramento;
    }
    public Usuario(short codigo, Usuario usuarioByAlteradoMultiploPor, Usuario usuarioByCodigo, GrupoUsuario grupoUsuario, Loja loja, String nome, String apelido, String senha, Boolean status, String email, Date criadoEm, Short criadoPor, Date alteradoEm, Short alteradoPor, Short ramal, Date dtNascimento, String sexo, String rg, String rgEstExp, String cpf, String nomePai, String nomeMae, String nomeConjuge, String estadoCivil, Short NFilhos, String nomeFilho1, String nomeFilho2, String nomeFilho3, String nomeFilho4, String nomeFilho5, String escolaridade, String escolaridadeNivel, String endRua, String endNumero, String endComplemento, String endBairro, String endCidade, String endCep, String endEstado, String telResidencial, String telContato, String nomeContato, String telCelular, Boolean alergico, String tipoAlergia, Boolean deveAlterarSenha, Date ultimaAlteracaoSenha, Boolean deveRecadastrar, Date ultimoRecadastramento, Boolean podeAlterarSenha, Date alteradoMultiploEm, short adiarRecadastramento, String foto, String observacoes, Boolean superAdministrador, Set usuariosForCodigo, Set servicosForAlteradoPor, Set usuariosForCodigo_1, Set usuariosForAlteradoMultiploPor, Set produtosesForAlteradoPor, Set crediarioClientesForModificadoPor, Set lojaFormaPagamentos, Set produtoMarcasForAlteradoPor, Set crediarioClientesForCadastradoPor, Set produtoMarcasForCriadoPor, Set fornecedoresesForAdicionadoPor, Set produtosesForCriadoPor, Set servicosForCriadoPor, Set fornecedoresesForModificadoPor, Set preVendas) {
       this.codigo = codigo;
       this.usuarioByAlteradoMultiploPor = usuarioByAlteradoMultiploPor;
       this.usuarioByCodigo = usuarioByCodigo;
       this.grupoUsuario = grupoUsuario;
       this.loja = loja;
       this.nome = nome;
       this.apelido = apelido;
       this.senha = senha;
       this.status = status;
       this.email = email;
       this.criadoEm = criadoEm;
       this.criadoPor = criadoPor;
       this.alteradoEm = alteradoEm;
       this.alteradoPor = alteradoPor;
       this.ramal = ramal;
       this.dtNascimento = dtNascimento;
       this.sexo = sexo;
       this.rg = rg;
       this.rgEstExp = rgEstExp;
       this.cpf = cpf;
       this.nomePai = nomePai;
       this.nomeMae = nomeMae;
       this.nomeConjuge = nomeConjuge;
       this.estadoCivil = estadoCivil;
       this.NFilhos = NFilhos;
       this.nomeFilho1 = nomeFilho1;
       this.nomeFilho2 = nomeFilho2;
       this.nomeFilho3 = nomeFilho3;
       this.nomeFilho4 = nomeFilho4;
       this.nomeFilho5 = nomeFilho5;
       this.escolaridade = escolaridade;
       this.escolaridadeNivel = escolaridadeNivel;
       this.endRua = endRua;
       this.endNumero = endNumero;
       this.endComplemento = endComplemento;
       this.endBairro = endBairro;
       this.endCidade = endCidade;
       this.endCep = endCep;
       this.endEstado = endEstado;
       this.telResidencial = telResidencial;
       this.telContato = telContato;
       this.nomeContato = nomeContato;
       this.telCelular = telCelular;
       this.alergico = alergico;
       this.tipoAlergia = tipoAlergia;
       this.deveAlterarSenha = deveAlterarSenha;
       this.ultimaAlteracaoSenha = ultimaAlteracaoSenha;
       this.deveRecadastrar = deveRecadastrar;
       this.ultimoRecadastramento = ultimoRecadastramento;
       this.podeAlterarSenha = podeAlterarSenha;
       this.alteradoMultiploEm = alteradoMultiploEm;
       this.adiarRecadastramento = adiarRecadastramento;
       this.foto = foto;
       this.observacoes = observacoes;
       this.superAdministrador = superAdministrador;
       this.usuariosForCodigo = usuariosForCodigo;
       this.servicosForAlteradoPor = servicosForAlteradoPor;
       this.usuariosForCodigo_1 = usuariosForCodigo_1;
       this.usuariosForAlteradoMultiploPor = usuariosForAlteradoMultiploPor;
       this.produtosesForAlteradoPor = produtosesForAlteradoPor;
       this.crediarioClientesForModificadoPor = crediarioClientesForModificadoPor;
       this.lojaFormaPagamentos = lojaFormaPagamentos;
       this.produtoMarcasForAlteradoPor = produtoMarcasForAlteradoPor;
       this.crediarioClientesForCadastradoPor = crediarioClientesForCadastradoPor;
       this.produtoMarcasForCriadoPor = produtoMarcasForCriadoPor;
       this.fornecedoresesForAdicionadoPor = fornecedoresesForAdicionadoPor;
       this.produtosesForCriadoPor = produtosesForCriadoPor;
       this.servicosForCriadoPor = servicosForCriadoPor;
       this.fornecedoresesForModificadoPor = fornecedoresesForModificadoPor;
       this.preVendas = preVendas;
    }
   
    public short getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(short codigo) {
        this.codigo = codigo;
    }
    public Usuario getUsuarioByAlteradoMultiploPor() {
        return this.usuarioByAlteradoMultiploPor;
    }
    
    public void setUsuarioByAlteradoMultiploPor(Usuario usuarioByAlteradoMultiploPor) {
        this.usuarioByAlteradoMultiploPor = usuarioByAlteradoMultiploPor;
    }
    public Usuario getUsuarioByCodigo() {
        return this.usuarioByCodigo;
    }
    
    public void setUsuarioByCodigo(Usuario usuarioByCodigo) {
        this.usuarioByCodigo = usuarioByCodigo;
    }
    public GrupoUsuario getGrupoUsuario() {
        return this.grupoUsuario;
    }
    
    public void setGrupoUsuario(GrupoUsuario grupoUsuario) {
        this.grupoUsuario = grupoUsuario;
    }
    public Loja getLoja() {
        return this.loja;
    }
    
    public void setLoja(Loja loja) {
        this.loja = loja;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getCriadoEm() {
        return this.criadoEm;
    }
    
    public void setCriadoEm(Date criadoEm) {
        this.criadoEm = criadoEm;
    }
    public Short getCriadoPor() {
        return this.criadoPor;
    }
    
    public void setCriadoPor(Short criadoPor) {
        this.criadoPor = criadoPor;
    }
    public Date getAlteradoEm() {
        return this.alteradoEm;
    }
    
    public void setAlteradoEm(Date alteradoEm) {
        this.alteradoEm = alteradoEm;
    }
    public Short getAlteradoPor() {
        return this.alteradoPor;
    }
    
    public void setAlteradoPor(Short alteradoPor) {
        this.alteradoPor = alteradoPor;
    }
    public Short getRamal() {
        return this.ramal;
    }
    
    public void setRamal(Short ramal) {
        this.ramal = ramal;
    }
    public Date getDtNascimento() {
        return this.dtNascimento;
    }
    
    public void setDtNascimento(Date dtNascimento) {
        this.dtNascimento = dtNascimento;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getRgEstExp() {
        return this.rgEstExp;
    }
    
    public void setRgEstExp(String rgEstExp) {
        this.rgEstExp = rgEstExp;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getNomePai() {
        return this.nomePai;
    }
    
    public void setNomePai(String nomePai) {
        this.nomePai = nomePai;
    }
    public String getNomeMae() {
        return this.nomeMae;
    }
    
    public void setNomeMae(String nomeMae) {
        this.nomeMae = nomeMae;
    }
    public String getNomeConjuge() {
        return this.nomeConjuge;
    }
    
    public void setNomeConjuge(String nomeConjuge) {
        this.nomeConjuge = nomeConjuge;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public Short getNFilhos() {
        return this.NFilhos;
    }
    
    public void setNFilhos(Short NFilhos) {
        this.NFilhos = NFilhos;
    }
    public String getNomeFilho1() {
        return this.nomeFilho1;
    }
    
    public void setNomeFilho1(String nomeFilho1) {
        this.nomeFilho1 = nomeFilho1;
    }
    public String getNomeFilho2() {
        return this.nomeFilho2;
    }
    
    public void setNomeFilho2(String nomeFilho2) {
        this.nomeFilho2 = nomeFilho2;
    }
    public String getNomeFilho3() {
        return this.nomeFilho3;
    }
    
    public void setNomeFilho3(String nomeFilho3) {
        this.nomeFilho3 = nomeFilho3;
    }
    public String getNomeFilho4() {
        return this.nomeFilho4;
    }
    
    public void setNomeFilho4(String nomeFilho4) {
        this.nomeFilho4 = nomeFilho4;
    }
    public String getNomeFilho5() {
        return this.nomeFilho5;
    }
    
    public void setNomeFilho5(String nomeFilho5) {
        this.nomeFilho5 = nomeFilho5;
    }
    public String getEscolaridade() {
        return this.escolaridade;
    }
    
    public void setEscolaridade(String escolaridade) {
        this.escolaridade = escolaridade;
    }
    public String getEscolaridadeNivel() {
        return this.escolaridadeNivel;
    }
    
    public void setEscolaridadeNivel(String escolaridadeNivel) {
        this.escolaridadeNivel = escolaridadeNivel;
    }
    public String getEndRua() {
        return this.endRua;
    }
    
    public void setEndRua(String endRua) {
        this.endRua = endRua;
    }
    public String getEndNumero() {
        return this.endNumero;
    }
    
    public void setEndNumero(String endNumero) {
        this.endNumero = endNumero;
    }
    public String getEndComplemento() {
        return this.endComplemento;
    }
    
    public void setEndComplemento(String endComplemento) {
        this.endComplemento = endComplemento;
    }
    public String getEndBairro() {
        return this.endBairro;
    }
    
    public void setEndBairro(String endBairro) {
        this.endBairro = endBairro;
    }
    public String getEndCidade() {
        return this.endCidade;
    }
    
    public void setEndCidade(String endCidade) {
        this.endCidade = endCidade;
    }
    public String getEndCep() {
        return this.endCep;
    }
    
    public void setEndCep(String endCep) {
        this.endCep = endCep;
    }
    public String getEndEstado() {
        return this.endEstado;
    }
    
    public void setEndEstado(String endEstado) {
        this.endEstado = endEstado;
    }
    public String getTelResidencial() {
        return this.telResidencial;
    }
    
    public void setTelResidencial(String telResidencial) {
        this.telResidencial = telResidencial;
    }
    public String getTelContato() {
        return this.telContato;
    }
    
    public void setTelContato(String telContato) {
        this.telContato = telContato;
    }
    public String getNomeContato() {
        return this.nomeContato;
    }
    
    public void setNomeContato(String nomeContato) {
        this.nomeContato = nomeContato;
    }
    public String getTelCelular() {
        return this.telCelular;
    }
    
    public void setTelCelular(String telCelular) {
        this.telCelular = telCelular;
    }
    public Boolean getAlergico() {
        return this.alergico;
    }
    
    public void setAlergico(Boolean alergico) {
        this.alergico = alergico;
    }
    public String getTipoAlergia() {
        return this.tipoAlergia;
    }
    
    public void setTipoAlergia(String tipoAlergia) {
        this.tipoAlergia = tipoAlergia;
    }
    public Boolean getDeveAlterarSenha() {
        return this.deveAlterarSenha;
    }
    
    public void setDeveAlterarSenha(Boolean deveAlterarSenha) {
        this.deveAlterarSenha = deveAlterarSenha;
    }
    public Date getUltimaAlteracaoSenha() {
        return this.ultimaAlteracaoSenha;
    }
    
    public void setUltimaAlteracaoSenha(Date ultimaAlteracaoSenha) {
        this.ultimaAlteracaoSenha = ultimaAlteracaoSenha;
    }
    public Boolean getDeveRecadastrar() {
        return this.deveRecadastrar;
    }
    
    public void setDeveRecadastrar(Boolean deveRecadastrar) {
        this.deveRecadastrar = deveRecadastrar;
    }
    public Date getUltimoRecadastramento() {
        return this.ultimoRecadastramento;
    }
    
    public void setUltimoRecadastramento(Date ultimoRecadastramento) {
        this.ultimoRecadastramento = ultimoRecadastramento;
    }
    public Boolean getPodeAlterarSenha() {
        return this.podeAlterarSenha;
    }
    
    public void setPodeAlterarSenha(Boolean podeAlterarSenha) {
        this.podeAlterarSenha = podeAlterarSenha;
    }
    public Date getAlteradoMultiploEm() {
        return this.alteradoMultiploEm;
    }
    
    public void setAlteradoMultiploEm(Date alteradoMultiploEm) {
        this.alteradoMultiploEm = alteradoMultiploEm;
    }
    public short getAdiarRecadastramento() {
        return this.adiarRecadastramento;
    }
    
    public void setAdiarRecadastramento(short adiarRecadastramento) {
        this.adiarRecadastramento = adiarRecadastramento;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }
    public Boolean getSuperAdministrador() {
        return this.superAdministrador;
    }
    
    public void setSuperAdministrador(Boolean superAdministrador) {
        this.superAdministrador = superAdministrador;
    }
    public Set getUsuariosForCodigo() {
        return this.usuariosForCodigo;
    }
    
    public void setUsuariosForCodigo(Set usuariosForCodigo) {
        this.usuariosForCodigo = usuariosForCodigo;
    }
    public Set getServicosForAlteradoPor() {
        return this.servicosForAlteradoPor;
    }
    
    public void setServicosForAlteradoPor(Set servicosForAlteradoPor) {
        this.servicosForAlteradoPor = servicosForAlteradoPor;
    }
    public Set getUsuariosForCodigo_1() {
        return this.usuariosForCodigo_1;
    }
    
    public void setUsuariosForCodigo_1(Set usuariosForCodigo_1) {
        this.usuariosForCodigo_1 = usuariosForCodigo_1;
    }
    public Set getUsuariosForAlteradoMultiploPor() {
        return this.usuariosForAlteradoMultiploPor;
    }
    
    public void setUsuariosForAlteradoMultiploPor(Set usuariosForAlteradoMultiploPor) {
        this.usuariosForAlteradoMultiploPor = usuariosForAlteradoMultiploPor;
    }
    public Set getProdutosesForAlteradoPor() {
        return this.produtosesForAlteradoPor;
    }
    
    public void setProdutosesForAlteradoPor(Set produtosesForAlteradoPor) {
        this.produtosesForAlteradoPor = produtosesForAlteradoPor;
    }
    public Set getCrediarioClientesForModificadoPor() {
        return this.crediarioClientesForModificadoPor;
    }
    
    public void setCrediarioClientesForModificadoPor(Set crediarioClientesForModificadoPor) {
        this.crediarioClientesForModificadoPor = crediarioClientesForModificadoPor;
    }
    public Set getLojaFormaPagamentos() {
        return this.lojaFormaPagamentos;
    }
    
    public void setLojaFormaPagamentos(Set lojaFormaPagamentos) {
        this.lojaFormaPagamentos = lojaFormaPagamentos;
    }
    public Set getProdutoMarcasForAlteradoPor() {
        return this.produtoMarcasForAlteradoPor;
    }
    
    public void setProdutoMarcasForAlteradoPor(Set produtoMarcasForAlteradoPor) {
        this.produtoMarcasForAlteradoPor = produtoMarcasForAlteradoPor;
    }
    public Set getCrediarioClientesForCadastradoPor() {
        return this.crediarioClientesForCadastradoPor;
    }
    
    public void setCrediarioClientesForCadastradoPor(Set crediarioClientesForCadastradoPor) {
        this.crediarioClientesForCadastradoPor = crediarioClientesForCadastradoPor;
    }
    public Set getProdutoMarcasForCriadoPor() {
        return this.produtoMarcasForCriadoPor;
    }
    
    public void setProdutoMarcasForCriadoPor(Set produtoMarcasForCriadoPor) {
        this.produtoMarcasForCriadoPor = produtoMarcasForCriadoPor;
    }
    public Set getFornecedoresesForAdicionadoPor() {
        return this.fornecedoresesForAdicionadoPor;
    }
    
    public void setFornecedoresesForAdicionadoPor(Set fornecedoresesForAdicionadoPor) {
        this.fornecedoresesForAdicionadoPor = fornecedoresesForAdicionadoPor;
    }
    public Set getProdutosesForCriadoPor() {
        return this.produtosesForCriadoPor;
    }
    
    public void setProdutosesForCriadoPor(Set produtosesForCriadoPor) {
        this.produtosesForCriadoPor = produtosesForCriadoPor;
    }
    public Set getServicosForCriadoPor() {
        return this.servicosForCriadoPor;
    }
    
    public void setServicosForCriadoPor(Set servicosForCriadoPor) {
        this.servicosForCriadoPor = servicosForCriadoPor;
    }
    public Set getFornecedoresesForModificadoPor() {
        return this.fornecedoresesForModificadoPor;
    }
    
    public void setFornecedoresesForModificadoPor(Set fornecedoresesForModificadoPor) {
        this.fornecedoresesForModificadoPor = fornecedoresesForModificadoPor;
    }
    public Set getPreVendas() {
        return this.preVendas;
    }
    
    public void setPreVendas(Set preVendas) {
        this.preVendas = preVendas;
    }




}


