/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sinetic.pafecftef.ui;

import br.com.sinetic.pafecftef.action.ACrediario;
import br.com.sinetic.pafecftef.action.Controller;
import br.com.sinetic.pafecftef.remoteentities.CrediarioFormaPagamento;
import br.com.sinetic.pafecftef.remoteentities.CrediarioFormaPagamentoDetalhado;
import br.com.sinetic.pafecftef.remoteentities.CrediarioVendaParcelamento;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author Windows8
 */
public class UICrediario extends javax.swing.JPanel {

    private ACrediario aC;
    
    //Modelo utilizado na lista dos meios de pagamento
    private DefaultListModel listaMP;
    
    /**
     * Creates new form UICrediario
     */
    public UICrediario() {
        initComponents();
        listaMP = new DefaultListModel();
        jlPagConf.setModel(listaMP);
    }

    public void setAction(ACrediario a) {
        aC = a;
    }
    
    public void clear() {
        listaMP.clear();
    }
    
    public void setPagamentoMeios(List<CrediarioFormaPagamento> lCFP) {
        Vector<String> v = new Vector();
        String s = null;
        for (CrediarioFormaPagamento cfp: lCFP) {
            s = cfp.getNome();
            v.add(s);
        }
        
        //Cria novo modelo
        ComboBoxModel cbm = new DefaultComboBoxModel(v);
        jcbMeiosDePag.setModel(cbm);
        
        if (v.size() > 0) {
            cbm.setSelectedItem(lCFP.get(0).getNome());
            aC.meioPagamentoSelected(jcbMeiosDePag.getSelectedIndex());
        }
    }
    
    public void setPagamentoTipos(Set<CrediarioFormaPagamentoDetalhado> sCFPD) {
        Vector<String> v = new Vector();
        String s = null;
        
        if (sCFPD == null || sCFPD.isEmpty()) {
            jcbTipo.setEnabled(false);
        }
        else {
            jcbTipo.setEnabled(true);
            for (CrediarioFormaPagamentoDetalhado cfpd: sCFPD) {
                s = cfpd.getNome();
                v.add(s);
            }
        }
        
        //Cria novo modelo
        ComboBoxModel cbm = new DefaultComboBoxModel(v);
        jcbTipo.setModel(cbm);
        
        if (v.size() > 0) {
            cbm.setSelectedItem(v.get(0));
        }
    }
    
    
    
    public boolean setInfoParcela(CrediarioVendaParcelamento cvp) {
        if (cvp == null) {
            return false;
        }
        
        jlVendaNum.setText(String.valueOf(cvp.getPreVenda().getCodigo()));
        jlCrediario.setText(String.valueOf(cvp.getCodigo()));
        jlCliente.setText(cvp.getPreVenda().getCrediarioCliente().getNome());
        jlCF.setText("COLOCAR CUPOM");
        jlValorTotal.setText("R$ " + cvp.getPreVenda().getValorFinal());
        float vr = aC.getValorRestante();
        jlValorRestante.setText("R$ " + vr);
        int npt = aC.getNumParcelasTotal();
        jlNumParcelas.setText(""+npt);
        int npa = aC.getNumParcelasAtual();
        jlNumParcelas.setText(""+npa);
        jlParcelaReceber.setText("R$ " + cvp.getParcelaValor());
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jcbMeiosDePag = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jbEfetuarPag = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox();
        jftfValor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlPagConf = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        jlTroco = new javax.swing.JLabel();
        jlTotalPag = new javax.swing.JLabel();
        jbFinalizaVenda = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jlVendaNum = new javax.swing.JLabel();
        jlCrediario = new javax.swing.JLabel();
        jlCliente = new javax.swing.JLabel();
        jlCF = new javax.swing.JLabel();
        jlValorTotal = new javax.swing.JLabel();
        jlNumParcelas = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jlParcelaAtual = new javax.swing.JLabel();
        jlParcelaReceber = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jlValorRestante = new javax.swing.JLabel();

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Realizar Pagamento"));

        jcbMeiosDePag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMeiosDePagActionPerformed(evt);
            }
        });

        jLabel8.setText("Meio de Pagamento:");

        jLabel12.setText("Valor:");

        jbEfetuarPag.setText("Efetuar Pagamento");
        jbEfetuarPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEfetuarPagActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo:");

        jcbTipo.setEnabled(false);

        jftfValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jftfValor.setText("0");
        jftfValor.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbMeiosDePag, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbEfetuarPag, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jftfValor)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbMeiosDePag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jftfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbEfetuarPag)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagamentos Confirmados"));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("Total Pagamentos:");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Troco:");

        jScrollPane2.setViewportView(jlPagConf);

        jButton3.setText("Estorna Pagamento");

        jlTroco.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jlTroco.setText("R$ 0,00");

        jlTotalPag.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jlTotalPag.setText("R$ 0,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlTroco)
                                    .addComponent(jlTotalPag)))
                            .addComponent(jButton3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jlTroco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlTotalPag))
                .addContainerGap())
        );

        jbFinalizaVenda.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        jbFinalizaVenda.setText("Finalizar Pagamento");
        jbFinalizaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFinalizaVendaActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes"));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("Venda Núm:");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setText("Cupom Fiscal:");

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setText("Valor Total:");

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setText("Número de Parcelas:");

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel13.setText("Parcela a Receber:");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setText("Cliente:");

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel15.setText("Crediário:");

        jlVendaNum.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jlVendaNum.setText("000000");

        jlCrediario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlCrediario.setText("000000");

        jlCliente.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlCliente.setText("Nome do Cliente");

        jlCF.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlCF.setText("000000");

        jlValorTotal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlValorTotal.setText("R$ 0,00");

        jlNumParcelas.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlNumParcelas.setText("0");

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel16.setText("Parcela Atual:");

        jlParcelaAtual.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlParcelaAtual.setText("0");

        jlParcelaReceber.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jlParcelaReceber.setText("R$ 0,00");

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel17.setText("Valor Restante:");

        jlValorRestante.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jlValorRestante.setText("R$ 0,00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlVendaNum))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlCrediario))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlCliente))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlCF))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlValorTotal))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlNumParcelas))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jlParcelaReceber))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlParcelaAtual))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlValorRestante)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlVendaNum))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jlCrediario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jlCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jlCF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jlValorTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jlValorRestante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jlNumParcelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jlParcelaAtual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jlParcelaReceber))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbFinalizaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbFinalizaVenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbMeiosDePagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMeiosDePagActionPerformed
        aC.meioPagamentoSelected(jcbMeiosDePag.getSelectedIndex());
    }//GEN-LAST:event_jcbMeiosDePagActionPerformed

    private void jbEfetuarPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEfetuarPagActionPerformed
        float valor;
        try  {
            valor = Float.valueOf((String)jftfValor.getText());
        }
        catch (Exception e) {
            Controller.messageBox("Valor inválido!");
            return;
        }
        
        if (valor <= 0) {
            Controller.messageBox("Valor inválido! \nValor não pode ser zero ou negativo.");
            return;
        }
        
        if (aC.checaNovoPagamento(valor)) {
            
           
            int iMeio = jcbMeiosDePag.getSelectedIndex();
            int iTipo = jcbTipo.getSelectedIndex();
            if (aC.efetuarPagamento(valor, iMeio, iTipo)) {
                String sTipo = aC.getPagTipo(iMeio, iTipo);
                listaMP.addElement("" + aC.getPagMeio(iMeio).toUpperCase() + (sTipo!=null?(" "+sTipo.toUpperCase()):"") + ": R$ "+ valor);
                //Atualiza o total pago
                jlTotalPag.setText("R$ " + aC.getTotalPago());
                jlTroco.setText("R$ " + aC.getTroco());
            }
        }
        else {
            Controller.messageBox("Não há necessidade de novo pagamento \n Favor fechar o Cupom Fiscal!");
        }
    }//GEN-LAST:event_jbEfetuarPagActionPerformed

    private void jbFinalizaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFinalizaVendaActionPerformed
        if (aC.checaValorTotalParaFecharCNF()) {
            if (aC.fechaPagamento()) {
                Controller.messageBox("Pagamento concluído com sucesso!");
                Controller.mudarEstado(Controller.ESTADO_LVENDAS);
            }
            else {
                Controller.messageBox("Erro ao fechar o Cupom Não Fiscal!");
            }
        }
        else {
            Controller.messageBox("Não há pagamento suficiente para fechar o Cupom Não Fiscal!");
        }
    }//GEN-LAST:event_jbFinalizaVendaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbEfetuarPag;
    private javax.swing.JButton jbFinalizaVenda;
    private javax.swing.JComboBox jcbMeiosDePag;
    private javax.swing.JComboBox jcbTipo;
    private javax.swing.JTextField jftfValor;
    private javax.swing.JLabel jlCF;
    private javax.swing.JLabel jlCliente;
    private javax.swing.JLabel jlCrediario;
    private javax.swing.JLabel jlNumParcelas;
    private javax.swing.JList jlPagConf;
    private javax.swing.JLabel jlParcelaAtual;
    private javax.swing.JLabel jlParcelaReceber;
    private javax.swing.JLabel jlTotalPag;
    private javax.swing.JLabel jlTroco;
    private javax.swing.JLabel jlValorRestante;
    private javax.swing.JLabel jlValorTotal;
    private javax.swing.JLabel jlVendaNum;
    // End of variables declaration//GEN-END:variables
}
